"""core/effects_catalog.py — Thư viện hiệu ứng custom_js VIP làm few-shot cho AI.

QUAN TRỌNG — cỡ chữ theo độ phân giải: canvas RỘNG 1080px (9:16) / 1920px (16:9).
Font trong custom_js phải LỚN để đọc được khi xem trên điện thoại:
  - Nhãn/label: 26–34px    - Tiêu đề phụ trong hình: 32–40px
  - Số liệu lớn: 60–110px  - KHÔNG dùng font < 24px.
Bán kính/thanh/khối cũng scale to tương ứng; return height 460–620 để lấp khung.

Biến có sẵn: ctx, W (1080), cursorY, stepProgress (0→1), time (giây),
rc(name) → màu 'green'|'cyan'|'yellow'|'red'|'white'.
Quy ước: ctx.save() ... ctx.restore();return <height>;
"""
EFFECTS = [{"name": "counter_metric", "when": "khoe con số lớn tăng dần / chỉ số quan trọng (doanh thu, %, số lượng)", "code": "ctx.save();const cx=W/2,cy=cursorY+230;const val=Math.floor(stepProgress*100);const pulse=1+0.05*Math.sin(time*3);ctx.save();ctx.translate(cx,cy);ctx.scale(pulse,pulse);ctx.fillStyle=rc('green');ctx.font='bold 160px monospace';ctx.textAlign='center';ctx.shadowColor=rc('green');ctx.shadowBlur=40;ctx.fillText(val+'%',0,0);ctx.restore();ctx.shadowBlur=0;ctx.fillStyle='rgba(148,163,184,0.95)';ctx.font='bold 30px monospace';ctx.textAlign='center';ctx.fillText('TĂNG TRƯỞNG THỰC TẾ',cx,cy+110);const bw=560,bx=cx-bw/2,by=cy+150;ctx.fillStyle='rgba(255,255,255,0.10)';ctx.beginPath();ctx.roundRect(bx,by,bw,18,9);ctx.fill();ctx.fillStyle=rc('green');ctx.save();ctx.shadowColor=rc('green');ctx.shadowBlur=18;ctx.beginPath();ctx.roundRect(bx,by,bw*stepProgress,18,9);ctx.fill();ctx.restore();ctx.restore();return 520;"},
    {"name": "bar_compare", "when": "so sánh 2 giá trị (trước/sau, rẻ/đắt, A/B)", "code": "ctx.save();const cx=W/2,cy=cursorY+220;function bar(label,emoji,val,maxVal,col,y){ctx.fillStyle='#fff';ctx.font='bold 28px monospace';ctx.textAlign='left';ctx.fillText(emoji+'  '+label,cx-320,y-24);ctx.fillStyle='rgba(255,255,255,0.08)';ctx.beginPath();ctx.roundRect(cx-320,y,640,52,14);ctx.fill();const w=640*val/maxVal*stepProgress;ctx.fillStyle=col;ctx.save();ctx.shadowColor=col;ctx.shadowBlur=18;ctx.beginPath();ctx.roundRect(cx-320,y,w,52,14);ctx.fill();ctx.restore();ctx.fillStyle='#fff';ctx.font='bold 26px monospace';ctx.textAlign='right';ctx.fillText(Math.round(val*stepProgress),cx+308,y+36);}bar('CÁCH CŨ','🐌',35,100,rc('red'),cy-90);bar('CÁCH MỚI','🚀',88,100,rc('green'),cy+50);ctx.fillStyle=rc('yellow');ctx.font='bold 32px monospace';ctx.textAlign='center';ctx.fillText('CHÊNH LỆCH RÕ RỆT ⚡',cx,cy+180);ctx.restore();return 540;"},
    {"name": "growth_curve", "when": "đường cong tăng trưởng theo thời gian, xu hướng đi lên, hiệu ứng tích lũy", "code": "ctx.save();const cx=W/2,cy=cursorY+240;const lx=cx-320,rx=cx+320,by=cy+120,ty=cy-150;ctx.strokeStyle='rgba(255,255,255,0.18)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(lx,by);ctx.lineTo(rx,by);ctx.moveTo(lx,by);ctx.lineTo(lx,ty);ctx.stroke();const P=Math.max(0.02,stepProgress);ctx.strokeStyle=rc('green');ctx.lineWidth=7;ctx.save();ctx.shadowColor=rc('green');ctx.shadowBlur=22;ctx.beginPath();let lastX=lx,lastY=by;for(let i=0;i<=100*P;i++){const t=i/100;const x=lx+(rx-lx)*t;const k=10*(t-0.5);const s=1/(1+Math.exp(-k));const y=by-(by-ty)*s;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);lastX=x;lastY=y;}ctx.stroke();ctx.restore();ctx.fillStyle=rc('yellow');ctx.save();ctx.shadowColor=rc('yellow');ctx.shadowBlur=24;ctx.beginPath();ctx.arc(lastX,lastY,12,0,Math.PI*2);ctx.fill();ctx.restore();ctx.fillStyle=rc('cyan');ctx.font='bold 32px monospace';ctx.textAlign='center';ctx.fillText('ĐÀ TĂNG THEO THỜI GIAN 📈',cx,cy+170);ctx.restore();return 540;"},
    {"name": "orbit_ecosystem", "when": "một trung tâm với nhiều yếu tố xoay quanh (hệ sinh thái, kênh, nền tảng)", "code": "ctx.save();const cx=W/2,cy=cursorY+240;ctx.font='80px sans-serif';ctx.textAlign='center';ctx.fillText('🎯',cx,cy+24);ctx.strokeStyle='rgba(34,211,238,0.22)';ctx.setLineDash([6,7]);ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(cx,cy,200,140,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);const items=['📱','💻','📺','📰','🎬','📢'];for(let i=0;i<items.length;i++){const reveal=Math.max(0,Math.min(1,stepProgress*7-i*0.6));if(reveal<=0)continue;const a=time*0.6+i*Math.PI*2/items.length;const x=cx+Math.cos(a)*200;const y=cy+Math.sin(a)*140;const pulse=1+0.1*Math.sin(time*3+i);ctx.save();ctx.globalAlpha=reveal;ctx.fillStyle='rgba(15,23,42,0.95)';ctx.strokeStyle=rc('yellow');ctx.lineWidth=3;ctx.shadowColor=rc('yellow');ctx.shadowBlur=18*pulse;ctx.beginPath();ctx.arc(x,y,38*pulse,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();ctx.fillStyle='#fff';ctx.font='34px sans-serif';ctx.fillText(items[i],x,y+12);}ctx.fillStyle=rc('yellow');ctx.font='bold 32px monospace';ctx.textAlign='center';ctx.fillText('PHỦ SÓNG MỌI KÊNH',cx,cy+210);ctx.restore();return 560;"},
    {"name": "step_reveal_list", "when": "liệt kê 3-4 bước / ý chính hiện lần lượt (checklist, quy trình)", "code": "ctx.save();const cx=W/2,cy=cursorY+180;const items=[['📌','Xác định mục tiêu rõ ràng',rc('cyan')],['🎯','Chọn đúng phương pháp',rc('yellow')],['⚡','Thực thi nhất quán',rc('green')],['📈','Đo lường & tối ưu',rc('red')]];const rowH=96;ctx.textAlign='left';for(let i=0;i<items.length;i++){const reveal=Math.max(0,Math.min(1,stepProgress*5-i));if(reveal<=0)continue;const ry=cy-180+i*rowH;const slide=(1-reveal)*60;ctx.save();ctx.globalAlpha=reveal;ctx.fillStyle='rgba(255,255,255,0.05)';ctx.strokeStyle=items[i][2];ctx.lineWidth=3;ctx.shadowColor=items[i][2];ctx.shadowBlur=14;ctx.beginPath();ctx.roundRect(cx-420+slide,ry,840,76,16);ctx.fill();ctx.stroke();ctx.restore();ctx.fillStyle=items[i][2];ctx.beginPath();ctx.arc(cx-382+slide,ry+38,26,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0f172a';ctx.font='bold 26px sans-serif';ctx.textAlign='center';ctx.fillText(i+1,cx-382+slide,ry+47);ctx.font='40px sans-serif';ctx.fillStyle='#fff';ctx.fillText(items[i][0],cx-330+slide,ry+52);ctx.textAlign='left';ctx.fillStyle='#e2e8f0';ctx.font='bold 30px sans-serif';ctx.fillText(items[i][1],cx-280+slide,ry+48);}ctx.restore();return 560;"},
    {"name": "gauge_dial", "when": "mức độ / ngưỡng (tần suất, rủi ro, tốc độ) với vùng xanh-vàng-đỏ", "code": "ctx.save();const gx=W/2,gy=cursorY+250,r=170;ctx.lineWidth=36;ctx.lineCap='round';ctx.strokeStyle=rc('green');ctx.beginPath();ctx.arc(gx,gy,r,Math.PI,Math.PI+Math.PI*0.5);ctx.stroke();ctx.strokeStyle=rc('yellow');ctx.beginPath();ctx.arc(gx,gy,r,Math.PI+Math.PI*0.5,Math.PI+Math.PI*0.8);ctx.stroke();ctx.strokeStyle=rc('red');ctx.beginPath();ctx.arc(gx,gy,r,Math.PI+Math.PI*0.8,Math.PI*2);ctx.stroke();const frac=0.15+0.6*stepProgress+0.05*Math.sin(time*1.5);const ang=Math.PI+Math.PI*Math.min(0.95,frac);ctx.strokeStyle='#fff';ctx.lineWidth=9;ctx.save();ctx.shadowColor='#fff';ctx.shadowBlur=14;ctx.beginPath();ctx.moveTo(gx,gy);ctx.lineTo(gx+Math.cos(ang)*(r-26),gy+Math.sin(ang)*(r-26));ctx.stroke();ctx.restore();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(gx,gy,15,0,Math.PI*2);ctx.fill();ctx.fillStyle=rc('cyan');ctx.font='bold 34px monospace';ctx.textAlign='center';ctx.fillText('MỨC TỐI ƯU',gx,gy+90);ctx.restore();return 520;"},
    {"name": "flow_pipeline", "when": "luồng chuyển hóa A → B → C, phễu, quy trình có mũi tên", "code": "ctx.save();const cy=cursorY+240;const nodes=[['🌱','ĐẦU VÀO',rc('cyan')],['⚙️','XỬ LÝ',rc('yellow')],['💎','KẾT QUẢ',rc('green')]];const n=nodes.length;const gap=W*0.64/(n-1);const sx=W/2-W*0.32;for(let i=0;i<n;i++){const reveal=Math.max(0,Math.min(1,stepProgress*4-i*1.1));if(reveal<=0)continue;const x=sx+i*gap;ctx.save();ctx.globalAlpha=reveal;const pulse=1+0.05*Math.sin(time*3+i);ctx.fillStyle='rgba(15,23,42,0.95)';ctx.strokeStyle=nodes[i][2];ctx.lineWidth=5;ctx.shadowColor=nodes[i][2];ctx.shadowBlur=24*pulse;ctx.beginPath();ctx.arc(x,cy,74*pulse,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();ctx.fillStyle='#fff';ctx.font='56px sans-serif';ctx.textAlign='center';ctx.fillText(nodes[i][0],x,cy+20);ctx.fillStyle=nodes[i][2];ctx.font='bold 28px monospace';ctx.fillText(nodes[i][1],x,cy+120);if(i<n-1){const t=(time*0.8+i*0.3)%1;const ax=x+74,bx=x+gap-74;ctx.fillStyle=rc('yellow');ctx.save();ctx.shadowColor=rc('yellow');ctx.shadowBlur=12;ctx.beginPath();ctx.arc(ax+(bx-ax)*t,cy,9,0,Math.PI*2);ctx.fill();ctx.restore();}}ctx.restore();return 500;"},
    {"name": "leak_bucket", "when": "rò rỉ / thất thoát / giữ chân (nước vào trên, rò dưới)", "code": "ctx.save();const cx=W/2,cy=cursorY+250;for(let i=0;i<3;i++){const t=(time*1.4+i/3)%1;ctx.save();ctx.globalAlpha=1-t*0.5;ctx.fillStyle=rc('cyan');ctx.shadowColor=rc('cyan');ctx.shadowBlur=10;ctx.beginPath();ctx.arc(cx+(i-1)*24,cy-150+t*80,9,0,Math.PI*2);ctx.fill();ctx.restore();}const topW=320,botW=240,bh=220,ty=cy-70;ctx.strokeStyle='rgba(255,255,255,0.6)';ctx.lineWidth=7;ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(cx-topW/2,ty);ctx.lineTo(cx-botW/2,ty+bh);ctx.lineTo(cx+botW/2,ty+bh);ctx.lineTo(cx+topW/2,ty);ctx.stroke();const lvl=0.5+0.1*Math.sin(time*1.2);const wy=ty+bh-bh*lvl;const wTop=botW+(topW-botW)*lvl;ctx.fillStyle='rgba(34,211,238,0.28)';ctx.beginPath();ctx.moveTo(cx-wTop/2,wy);ctx.lineTo(cx-botW/2,ty+bh);ctx.lineTo(cx+botW/2,ty+bh);ctx.lineTo(cx+wTop/2,wy);ctx.closePath();ctx.fill();for(let i=0;i<3;i++){const t=(time*1.6+i/3)%1;ctx.save();ctx.globalAlpha=1-t;ctx.fillStyle=rc('red');ctx.shadowColor=rc('red');ctx.shadowBlur=10;ctx.beginPath();ctx.arc(cx-50+i*50,ty+bh+8+t*70,9,0,Math.PI*2);ctx.fill();ctx.restore();}ctx.fillStyle=rc('yellow');ctx.font='bold 32px monospace';ctx.textAlign='center';ctx.fillText('BỊT LỖ RÒ RỈ 🪣',cx,cy+210);ctx.restore();return 560;"},
    {"name": "flat_stat", "when": "khoe MỘT con số lớn kiểu phẳng, tối giản, không hào quang", "code": "ctx.save();const cx=W/2,cy=cursorY+230;const val=Math.floor(stepProgress*100);ctx.fillStyle=rc('white');ctx.globalAlpha=0.06;ctx.beginPath();ctx.roundRect(cx-310,cy-150,620,320,30);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=rc('cyan');ctx.font='bold 190px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(val+'%',cx,cy-6);ctx.textBaseline='alphabetic';const bw=520,bx=cx-bw/2,by=cy+96;ctx.fillStyle='rgba(255,255,255,0.10)';ctx.beginPath();ctx.roundRect(bx,by,bw,14,7);ctx.fill();ctx.fillStyle=rc('cyan');ctx.beginPath();ctx.roundRect(bx,by,bw*stepProgress,14,7);ctx.fill();ctx.fillStyle=rc('white');ctx.font='bold 30px sans-serif';ctx.textAlign='center';ctx.fillText('CHỈ SỐ NỔI BẬT',cx,cy+150);ctx.restore();return 500;"},
    {"name": "donut_percent", "when": "phần trăm dạng vòng tròn donut sạch sẽ, không glow", "code": "ctx.save();const cx=W/2,cy=cursorY+230,r=155;const P=Math.max(0.02,stepProgress);ctx.lineWidth=46;ctx.lineCap='round';ctx.strokeStyle='rgba(255,255,255,0.10)';ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=rc('green');ctx.beginPath();ctx.arc(cx,cy,r,-Math.PI/2,-Math.PI/2+Math.PI*2*P);ctx.stroke();ctx.fillStyle=rc('white');ctx.font='bold 96px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(Math.floor(P*100)+'%',cx,cy);ctx.textBaseline='alphabetic';ctx.fillStyle=rc('green');ctx.font='bold 30px sans-serif';ctx.fillText('TIẾN ĐỘ HOÀN THÀNH',cx,cy+r+66);ctx.restore();return 500;"},
    {"name": "star_rating", "when": "đánh giá sao (review, mức hài lòng, chất lượng)", "code": "ctx.save();const cx=W/2,cy=cursorY+210;const rating=4.7;const fill=stepProgress*rating;function starPath(x,y,R){const r=R*0.45;ctx.beginPath();for(let i=0;i<10;i++){const rad=i%2===0?R:r;const a=-Math.PI/2+i*Math.PI/5;const px=x+Math.cos(a)*rad,py=y+Math.sin(a)*rad;if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}ctx.closePath();}const gap=140,sx=cx-gap*2,R=56;for(let i=0;i<5;i++){const f=Math.max(0,Math.min(1,fill-i));const x=sx+i*gap;starPath(x,cy,R);ctx.strokeStyle=rc('yellow');ctx.lineWidth=5;ctx.stroke();if(f>0){ctx.save();ctx.beginPath();ctx.rect(x-R,cy-R,2*R*f,2*R);ctx.clip();starPath(x,cy,R);ctx.fillStyle=rc('yellow');ctx.fill();ctx.restore();}}ctx.fillStyle=rc('yellow');ctx.font='bold 74px sans-serif';ctx.textAlign='center';ctx.fillText(fill.toFixed(1),cx,cy+150);ctx.fillStyle=rc('white');ctx.font='bold 27px sans-serif';ctx.fillText('ĐÁNH GIÁ TRUNG BÌNH',cx,cy+205);ctx.restore();return 470;"},
    {"name": "timeline_road", "when": "dòng thời gian / cột mốc theo năm (lịch sử, lộ trình)", "code": "ctx.save();const cy=cursorY+240,lx=W/2-360,rx=W/2+360;ctx.strokeStyle='rgba(255,255,255,0.18)';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(lx,cy);ctx.lineTo(rx,cy);ctx.stroke();ctx.strokeStyle=rc('cyan');ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(lx,cy);ctx.lineTo(lx+(rx-lx)*stepProgress,cy);ctx.stroke();const L=[['2021','Khởi đầu'],['2022','Tăng tốc'],['2023','Bứt phá'],['2024','Dẫn đầu']];for(let i=0;i<4;i++){const t=i/3,x=lx+(rx-lx)*t,on=stepProgress>=t-0.03;ctx.fillStyle=on?rc('cyan'):'rgba(255,255,255,0.25)';ctx.beginPath();ctx.arc(x,cy,on?18:12,0,Math.PI*2);ctx.fill();ctx.fillStyle=rc('white');ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.fillText(L[i][0],x,cy-46);ctx.fillStyle='rgba(255,255,255,0.72)';ctx.font='25px sans-serif';ctx.fillText(L[i][1],x,cy+58);}ctx.restore();return 480;"},
    {"name": "quote_card", "when": "câu trích dẫn / châm ngôn nổi bật (động lực, kết luận)", "code": "ctx.save();const cx=W/2,cy=cursorY+210;ctx.globalAlpha=Math.min(1,stepProgress*1.6);ctx.fillStyle=rc('yellow');ctx.font='bold 170px Georgia, serif';ctx.textAlign='center';ctx.fillText('“',cx-330,cy-30);ctx.fillStyle=rc('white');ctx.font='bold 48px sans-serif';const lines=['Thành công là tổng của','những nỗ lực nhỏ','lặp lại mỗi ngày.'];lines.forEach((l,i)=>ctx.fillText(l,cx,cy-30+i*70));ctx.strokeStyle=rc('cyan');ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx-70,cy+180);ctx.lineTo(cx+70,cy+180);ctx.stroke();ctx.fillStyle=rc('cyan');ctx.font='27px sans-serif';ctx.fillText('CHÂM NGÔN',cx,cy+220);ctx.restore();return 480;"},
    {"name": "icon_grid", "when": "lưới 6 tính năng/yếu tố có icon (tổng quan, tính năng)", "code": "ctx.save();const items=[['🎯','Mục tiêu'],['⚡','Tốc độ'],['💡','Ý tưởng'],['📈','Tăng trưởng'],['🛡️','An toàn'],['🤝','Hợp tác']];const cw=250,ch=175,gx=W/2-cw,gy=cursorY+130;for(let i=0;i<items.length;i++){const c=i%3,r=Math.floor(i/3);const reveal=Math.max(0,Math.min(1,stepProgress*7-i*0.8));if(reveal<=0)continue;const x=gx+c*cw,y=gy+r*ch;ctx.save();ctx.globalAlpha=reveal;ctx.fillStyle='rgba(255,255,255,0.06)';ctx.strokeStyle='rgba(255,255,255,0.18)';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(x-105,y-72,210,144,20);ctx.fill();ctx.stroke();ctx.restore();ctx.font='56px sans-serif';ctx.textAlign='center';ctx.fillStyle='#fff';ctx.globalAlpha=reveal;ctx.fillText(items[i][0],x,y+2);ctx.fillStyle='rgba(255,255,255,0.85)';ctx.font='bold 25px sans-serif';ctx.fillText(items[i][1],x,y+56);ctx.globalAlpha=1;}ctx.restore();return 560;"},
    {"name": "breaking_news", "when": "tin công nghệ / breaking news / ra mắt / sáp nhập: badge BREAKING đàn hồi + 2 node phát sáng trượt lại gần nối bằng line gradient", "code": "ctx.save();\nfunction CL(v){return Math.max(0,Math.min(1,v));}\nfunction EB(t){var c1=1.70158,c3=c1+1;return 1+c3*Math.pow(t-1,3)+c1*Math.pow(t-1,2);}\nfunction EZ(t){return 1-Math.pow(1-t,3);}\nvar P=CL(stepProgress),cx=W/2,cy=cursorY+170;\nvar CLR=['rgba(255,255,255,','rgba(52,211,153,','rgba(96,165,250,','rgba(167,139,250,'];\nfor(var i=0;i<26;i++){var sx=((i*197)%(W-80))+40,sy=cy-220+((i*389)%440);var tw0=0.2+0.5*Math.abs(Math.sin(time*1.4+i*1.7));ctx.fillStyle=CLR[i%4]+tw0+')';ctx.beginPath();ctx.arc(sx,sy,(i%7===0)?2.6:1.5,0,Math.PI*2);ctx.fill();}\nvar lb='BREAKING · TIN NÓNG'.split('').join(' ');\nctx.font='bold 30px Consolas';var tw=ctx.measureText(lb).width+118,x=cx-tw/2,py=cy-150;\nvar ap=EB(CL(P*2.2));ctx.save();ctx.globalAlpha=Math.min(1,P*3);\nctx.translate(cx,py);ctx.scale(ap,1);ctx.translate(-cx,-py);\nctx.strokeStyle='rgba(140,170,255,0.55)';ctx.lineWidth=2.5;ctx.beginPath();ctx.roundRect(x,py-34,tw,68,34);ctx.stroke();\nctx.fillStyle='rgba(20,28,58,0.55)';ctx.beginPath();ctx.roundRect(x,py-34,tw,68,34);ctx.fill();\nvar bl=0.5+0.5*Math.sin(time*4.5);ctx.fillStyle='rgba(52,211,153,'+(0.5+0.5*bl)+')';ctx.shadowColor='#34d399';ctx.shadowBlur=12*bl;\nctx.beginPath();ctx.arc(x+40,py,8,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;\nctx.fillStyle='#dbe3ff';ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(lb,x+66,py+2);ctx.restore();\nvar ny=cy+50,lw=W*0.52;\nctx.strokeStyle='rgba(140,170,255,0.4)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx-lw/2,ny);ctx.lineTo(cx+lw/2,ny);ctx.stroke();\nvar mp=EZ(CL(P*1.5));var grd=ctx.createLinearGradient(cx-lw/2,0,cx+lw/2,0);grd.addColorStop(0,'rgba(96,165,250,0.9)');grd.addColorStop(1,'rgba(52,211,153,0.95)');\nctx.strokeStyle=grd;ctx.lineWidth=5;ctx.shadowColor='#34d399';ctx.shadowBlur=14;ctx.beginPath();ctx.moveTo(cx-lw/2,ny);ctx.lineTo(cx-lw/2+lw*mp,ny);ctx.stroke();ctx.shadowBlur=0;\nvar gap=(1-mp)*180+130,r1x=cx-gap/2,r2x=cx+gap/2;\nctx.fillStyle='rgba(11,15,30,0.92)';\nctx.strokeStyle='#60a5fa';ctx.lineWidth=4;ctx.shadowColor='#60a5fa';ctx.shadowBlur=16;ctx.beginPath();ctx.arc(r1x,ny,42,0,Math.PI*2);ctx.fill();ctx.stroke();\nctx.strokeStyle='#34d399';ctx.shadowColor='#34d399';ctx.shadowBlur=18+8*Math.sin(time*3);ctx.beginPath();ctx.arc(r2x,ny,46,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;\nctx.fillStyle='#e2e8f0';ctx.font='bold 34px Consolas';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('×',cx,ny+2);\nctx.fillStyle='rgba(148,163,184,0.95)';ctx.font='bold 28px Consolas';ctx.fillText('// CHÍNH THỨC HỢP NHẤT',cx,ny+130);\nctx.restore();return 540;"}]
try:
    from core.custom_scenes import demo_effects as _cs_demo
    _existing = {e["name"] for e in EFFECTS}
    EFFECTS += [e for e in _cs_demo() if e["name"] not in _existing]
except Exception:
    pass


def catalog_for_prompt(n: int = 4, prefer=None) -> str:
    """Return a capped few-shot catalog, with preferred effects first."""
    by_name = {e["name"]: e for e in EFFECTS}
    picks, seen = [], set()
    for name in prefer or []:
        e = by_name.get(name)
        if not e or name in seen:
            continue
        picks.append(e)
        seen.add(name)
    for e in EFFECTS:
        if len(picks) >= n:
            break
        if e["name"] in seen:
            continue
        picks.append(e)
        seen.add(e["name"])
    return "\n\n".join(
        f"// [{e['name']}] Dùng khi: {e['when']}\n{e['code']}"
        for e in picks[:n]
    )


def effects_menu() -> str:
    return "\n".join(f"- {e['name']}: {e['when']}" for e in EFFECTS)
