"""core/scenes_mn_8.py — Bộ scene mathnoir #8: mn_definition_card, mn_zoom_lens.

Phong cách manim/3Blue1Brown: nền đen tuyền (renderer lo), nét trắng mảnh
lw3 tự vẽ nét dần, chữ xám nhỏ, accent (vàng/xanh) đúng 1 phần tử mỗi cảnh.
Xem mn_spec.md + mn2_spec.md.
"""
import json, random
from core.custom_scenes import scene; INK = "#e8e8ea"; MUTED = "#9a9aa0"; BODY = "#c9c9ce"; AXIS = "rgba(232,232,234,0.45)"; HAIR = "rgba(232,232,234,0.3)"; ACCENT = {"yellow": "#facc15", "blue": "#60a5fa"}
def _acc(name):
    return ACCENT.get(str(name), ACCENT["yellow"])

_TITLE_JS = "if(TITLE){ctx.globalAlpha=CL(P*2.2);ctx.font='600 34px Segoe UI, sans-serif';ctx.fillStyle='#8b8b92';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(TITLE,W/2,cursorY+40);ctx.globalAlpha=1;}"
def mn_definition_card(title="", term="tiên đề", pos="danh từ", definition="một mệnh đề được chấp nhận là đúng mà không cần chứng minh, làm cơ sở cho cả hệ thống lý luận.", accent="yellow", seed=0):
    ac = _acc(accent); _r = random.Random(12_345); lx = round(140 + _r.uniform(-30, 50)); tdy = round(300 + _r.uniform(-40, 28)); hw = round(220 * _r.uniform(0.82, 1.18)); lh = round(_r.uniform(50, 58))
    
    hairgap = round(_r.uniform(30, 50))
    
    defgap = round(_r.uniform(46, 84))
    
    tfs = round(96 * _r.uniform(0.85, 1.13))
    
    posdy = round(tfs * 0.77); hairdy = posdy + hairgap; y0dy = hairdy + defgap; clip_top = round(tfs * 0.75)
    
    clip_h = round(tfs * 1.5)
    return scene(["var TITLE=" + json.dumps(str(title), ensure_ascii=False) + ";", "var TERM=" + json.dumps(str(term), ensure_ascii=False) + ";", "var POS=" + json.dumps(str(pos), ensure_ascii=False) + ";", "var DEF=" + json.dumps(str(definition), ensure_ascii=False) + ";", "var ACC=" + json.dumps(ac) + ";", "ctx.save();", "ctx.lineCap='round';ctx.lineJoin='round';", _TITLE_JS, "/* idle: ca khoi noi dung troi nhe lien tuc theo time */", "ctx.translate(0,3*Math.sin(time*0.8));", "var LX=" + str(lx) + ", ty=cursorY+" + str(tdy) + ";", "ctx.textAlign='left';ctx.textBaseline='middle';", "/* ── term lon: HIEN DAN kieu viet (clip ngang theo e) ── */", "var e1=EZ(CL(P*1.5));", "ctx.font='bold " + str(tfs) + "px Segoe UI, sans-serif';", "var twd=ctx.measureText(TERM).width;", "if(e1>0.003){", "  ctx.save();ctx.beginPath();ctx.rect(LX-6,ty-" + str(clip_top) + ",(twd+20)*e1," + str(clip_h) + ");ctx.clip();", "  ctx.fillStyle='" + INK + "';", "  ctx.fillText(TERM,LX,ty);", "  ctx.restore();", "}", "/* ── pos: 30px italic muted — REVEAL MUON giua step (P2) ── */", "var e2=CL(P2*3-1.5);", "if(e2>0){", "  ctx.globalAlpha=e2;", "  ctx.font='italic 400 30px Segoe UI, sans-serif';ctx.fillStyle='" + MUTED + "';", "  ctx.fillText(POS,LX+4,ty+" + str(posdy) + "+10*(1-EZ(e2)));", "  ctx.globalAlpha=1;", "}", "/* ── gach ngang manh 220px VE DAN ── */", "var e3=EZ(CL(P*1.8-0.55));", "if(e3>0.003){", "  ctx.fillStyle='" + HAIR + "';",
    
    "  ctx.fillRect(LX,ty+" + str(hairdy) + "," + str(hw) + "*e3,2);", "}", "/* idle: cham trang nho truot qua lai doc gach ngang theo time */", "if(e3>0.95){", "  var dx=LX+" + str(hw) + "*(0.5+0.5*Math.sin(time*0.5));", "  ctx.globalAlpha=0.75;ctx.fillStyle='" + INK + "';", "  ctx.beginPath();ctx.arc(dx,ty+" + str(hairdy) + "+1,3,0,Math.PI*2);ctx.fill();", "  ctx.globalAlpha=1;", "}", "/* ── definition: wrap tay theo tu de to accent tu khoa = term ── */", "var maxW=W-" + str(lx + 140) + ", FDEF='400 34px Segoe UI, sans-serif';", "ctx.font=FDEF;", "function NRM(w){return w.toLowerCase().replace(/[.,;:!?()\\u2013\\u2014\\u2026\\u201c\\u201d]/g,'');}", "var words=DEF.split(/\\s+/).filter(function(w){return w.length>0;});", "var tws=TERM.split(/\\s+/).filter(function(w){return w.length>0;});", "/* tim chuoi tu dau tien trung term -> danh dau hot */", "var hi0=-1;", "if(tws.length>0){", "  for(var i=0;i+tws.length<=words.length;i++){", "    var ok=true;", "    for(var j=0;j<tws.length;j++){if(NRM(words[i+j])!==NRM(tws[j])){ok=false;break;}}", "    if(ok){hi0=i;break;}", "  }", "}", "var spw=ctx.measureText(' ').width;", "var lines=[], cur=[], cw=0;", "for(var k=0;k<words.length;k++){", "  var wd=ctx.measureText(words[k]).width;", "  var add=(cur.length?spw:0)+wd;", "  if(cur.length&&cw+add>maxW){lines.push(cur);cur=[];cw=0;add=wd;}", "  cur.push({t:words[k],w:wd,hot:(hi0>=0&&k>=hi0&&k<hi0+tws.length)});", "  cw+=add;", "}", "if(cur.length)lines.push(cur);", "lines=lines.slice(0,6);",
    
    "/* ── HIEN TUNG DONG: fade + truot len nhe, stagger ── */", "var y0=ty+" + str(y0dy) + ", LH=" + str(lh) + ";", "/* e6: gach chan accent duoi tu khoa hot — REVEAL MUON ~65% step */", "var e6=CL(P2*4-2.6);", "for(var li=0;li<lines.length;li++){", "  var la=CL(P*2.2-0.85-li*0.18);", "  if(la<=0)continue;", "  ctx.globalAlpha=la;", "  var yy=y0+li*LH+12*(1-EZ(la));", "  var xx=LX;", "  for(var wi=0;wi<lines[li].length;wi++){", "    var it=lines[li][wi];", "    if(it.hot){", "      /* idle: glow tho nhe tren tu khoa accent */", "      ctx.save();", "      ctx.shadowColor=ACC;ctx.shadowBlur=8+6*Math.sin(time*1.6);", "      ctx.fillStyle=ACC;", "      ctx.fillText(it.t,xx,yy);", "      ctx.restore();", "      if(e6>0.003){", "        ctx.save();ctx.globalAlpha=la*0.85*e6;ctx.fillStyle=ACC;", "        ctx.fillRect(xx,yy+24,it.w*EZ(e6),2);ctx.restore();", "      }", "    }else{", "      ctx.fillStyle='" + BODY + "';", "      ctx.fillText(it.t,xx,yy);", "    }", "    xx+=it.w+spw;", "  }", "  ctx.globalAlpha=1;", "}", "ctx.restore();"], 880)

def mn_zoom_lens(title="", behind="3.1415926535 8979323846", focus="926", label="chữ số thứ 8–10", accent="yellow", seed=0):
    ac = _acc(accent); _r = random.Random(12_345); cydy = round(430 + _r.uniform(-35, 25)); bias = round(_r.uniform(-45, 25)); amp = round(120 * _r.uniform(0.7, 1.08)); hl = round(170 * _r.uniform(0.82, 1.12))
    
    ha = round(_r.uniform(28, 42) * 3.14159 / 180, 3); fdy = round(118 * _r.uniform(0.82, 1.12))
    
    rr = round(190 * _r.uniform(0.85, 1.15))
    return scene(["var TITLE=" + json.dumps(str(title), ensure_ascii=False) + ";", "var BH=" + json.dumps(str(behind), ensure_ascii=False) + ";", "var FOC=" + json.dumps(str(focus), ensure_ascii=False) + ";", "var LBL=" + json.dumps(str(label), ensure_ascii=False) + ";", "var ACC=" + json.dumps(ac) + ";", "ctx.save();", "ctx.lineCap='round';ctx.lineJoin='round';ctx.textBaseline='middle';", _TITLE_JS, "var cy=cursorY+" + str(cydy) + ", r=" + str(rr) + ";", "/* ── dong so/chu dai mo chay ngang giua, co giam co neu qua rong ── */", "var bfs=40;", "ctx.font='400 '+bfs+'px Consolas, monospace';", "var bw0=ctx.measureText(BH).width;", "if(bw0>W-100){", "  bfs=Math.max(22,Math.floor(40*(W-100)/bw0));", "  ctx.font='400 '+bfs+'px Consolas, monospace';", "  bw0=ctx.measureText(BH).width;", "}", "var bx0=W/2-bw0/2;", "/* tam doan focus trong dong behind (de kinh lup 'neo' vao) */", "var fcx=W/2;",
    
    "var fi=BH.indexOf(FOC);", "if(fi>=0){", "  var pw=ctx.measureText(BH.slice(0,fi)).width;", "  var fw0=ctx.measureText(FOC).width;", "  fcx=bx0+pw+fw0/2;", "}", "/* HIEN DAN kieu viet: clip ngang */", "var e1=EZ(CL(P*1.7));", "if(e1>0.003){", "  ctx.save();ctx.beginPath();ctx.rect(bx0-6,cy-bfs,(bw0+12)*e1,bfs*2);ctx.clip();", "  ctx.fillStyle='rgba(232,232,234,0.35)';ctx.textAlign='left';", "  ctx.fillText(BH,bx0,cy);", "  ctx.restore();", "}", "/* ── kinh lup: di chuyen qua lai cham theo time ── */", "var e2=EZ(CL(P*1.4-0.2));", "var sway=CL(P*1.6-0.8);", "var lx=W/2" + "%+d" % bias + "+" + str(amp) + "*Math.sin(time*0.5)*sway;", "if(e2>0.003){", "  /* ben trong: nen toi + doan focus phong to 96px, clip theo vong */", "  var ef=CL(P*2.2-1.1);", "  if(ef>0.003){", "    ctx.save();", "    ctx.beginPath();ctx.arc(lx,cy,r-3,0,Math.PI*2);ctx.clip();", "    ctx.globalAlpha=0.85*ef;",
    
    "    ctx.fillStyle='#000';ctx.fillRect(lx-r,cy-r,r*2,r*2);", "    ctx.globalAlpha=ef;", "    /* parallax nhe: focus neo ve vi tri that trong dong behind */", "    var fx=lx+(fcx-lx)*0.45;", "    /* idle: so focus tho nhe (pulse scale) theo time */", "    var fsc=1+0.01*Math.sin(time*2);", "    ctx.translate(fx,cy);ctx.scale(fsc,fsc);ctx.translate(-fx,-cy);", "    ctx.font='bold 96px Consolas, monospace';ctx.fillStyle='#ffffff';", "    ctx.textAlign='center';", "    ctx.fillText(FOC,fx,cy);", "    ctx.globalAlpha=1;ctx.restore();", "  }", "  /* vien kinh VE NET DAN + idle: glow tho nhe theo time */", "  ctx.save();", "  ctx.shadowColor='rgba(255,255,255,0.6)';", "  ctx.shadowBlur=10+6*Math.sin(time*1.6);", "  ctx.strokeStyle='#ffffff';ctx.lineWidth=4;", "  ctx.beginPath();ctx.arc(lx,cy,r,-Math.PI/2,-Math.PI/2+Math.PI*2*e2);ctx.stroke();", "  ctx.restore();", "  /* anh kinh: cung glint ngan tren-trai — REVEAL MUON ~65% step */", "  var eg=CL(P2*4-2.6);", "  if(e2>0.999&&eg>0.003){", "    ctx.strokeStyle='rgba(255,255,255,'+(0.28*eg)+')';ctx.lineWidth=3;", "    ctx.beginPath();ctx.arc(lx,cy,r-22,Math.PI*1.08,Math.PI*1.34);ctx.stroke();", "  }", "  /* idle: cham trang nho chay quanh vien kinh theo time */", "  if(e2>0.999){", "    var da=-Math.PI/2+time*0.5;", "    ctx.fillStyle='#ffffff';", "    ctx.beginPath();ctx.arc(lx+Math.cos(da)*r,cy+Math.sin(da)*r,4,0,Math.PI*2);ctx.fill();", "  }", "  /* tay cam 30 do (duoi-phai), ve dan sau khi vien gan xong */", "  var eh=EZ(CL(P*1.8-0.85));", "  if(eh>0.003){", "    var ha=" + str(ha) + ";", "    var hx0=lx+Math.cos(ha)*(r+4), hy0=cy+Math.sin(ha)*(r+4);", "    var hl=" + str(hl) + "*eh;", "    ctx.strokeStyle='#ffffff';ctx.lineWidth=10;", "    ctx.beginPath();ctx.moveTo(hx0,hy0);", "    ctx.lineTo(hx0+Math.cos(ha)*hl,hy0+Math.sin(ha)*hl);ctx.stroke();", "  }", "}", "/* ── label accent duoi kinh + duong chi manh — REVEAL MUON giua step (P2) ── */", "var e4=CL(P2*3-1.5);", "if(e4>0.003){", "  ctx.globalAlpha=e4;", "  var ly=cy+r+" + str(fdy) + ";", "  ctx.strokeStyle='" + AXIS + "';ctx.lineWidth=2;",
    
    "  ctx.beginPath();ctx.moveTo(lx,cy+r+14);ctx.lineTo(lx,ly-32);ctx.stroke();", "  ctx.font='400 30px Segoe UI, sans-serif';ctx.fillStyle=ACC;", "  ctx.textAlign='center';", "  ctx.fillText(LBL,lx,ly);", "  ctx.globalAlpha=1;", "}", "ctx.restore();"], 860)

SCENES = {"mn_definition_card": {"fn": mn_definition_card, "doc": 'mn_definition_card {"title":"","term":"tiên đề","pos":"danh từ","definition":"...","accent":"yellow"} — thẻ thuật ngữ kiểu từ điển thuần typography: term 96px trắng viết dần, pos italic muted, gạch ngang mảnh, định nghĩa wrap hiện từng dòng (từ khoá trùng term tô accent)', "demo": {"title": "Thuật ngữ hôm nay", "term": "tiên đề", "pos": "danh từ", "definition": "một mệnh đề được chấp nhận là đúng mà không cần chứng minh — tiên đề là nền móng để xây cả hệ thống lý luận phía trên nó.", "accent": "yellow"}}, "mn_zoom_lens": {"fn": mn_zoom_lens, "doc": 'mn_zoom_lens {"title":"","behind":"3.1415926535 8979323846","focus":"926","label":"chữ số thứ 8–10","accent":"yellow"} — kính lúp viền trắng tự vẽ nét + tay cầm, lướt qua lại trên dãy số mờ; trong kính đoạn focus phóng to 96px trên nền tối, nhãn accent + đường chỉ dưới kính', "demo": {"title": "Soi vào π", "behind": "3.1415926535 8979323846", "focus": "926", "label": "chữ số thứ 8–10", "accent": "yellow"}}}
