"""core/scenes_mn_5.py — Bộ scene mathnoir #5: mn_big_symbol, mn_integral_area, mn_venn.

Phong cách manim/3Blue1Brown đợt 2: nền đen tuyền (renderer lo), nét trắng
mảnh lw3 TỰ VẼ NÉT dần, chữ xám nhỏ, accent vàng/xanh đúng 1 phần tử/cảnh.
Xem mn_spec.md + mn2_spec.md.
"""
import json, random
from core.custom_scenes import scene; INK = "#e8e8ea"; MUTED = "#9a9aa0"; AXIS = "rgba(232,232,234,0.45)"; DASH = "rgba(232,232,234,0.35)"; ACCENT = {"yellow": "#facc15", "blue": "#60a5fa"}; ACCENT_FILL = {"yellow": "rgba(250,204,21,", "blue": "rgba(96,165,250,"}
def _acc(name):
    return ACCENT.get(str(name), ACCENT["yellow"])

def _rng(seed):
    return random.Random((12_345 * 1_000_003 + 777) % 4294967296)

_TITLE_JS = "if(TITLE){ctx.globalAlpha=CL(P*2.2);ctx.font='600 34px Segoe UI, sans-serif';ctx.fillStyle='#8b8b92';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(TITLE,W/2,cursorY+40);ctx.globalAlpha=1;}"
def mn_big_symbol(title="", symbol="π", sub="tỉ số chu vi và đường kính", accent=False, seed=0):
    col = INK; _r = _rng(seed); _cy = round(490 + _r.uniform(-25, 20)); _ring = round(360 * _r.uniform(0.88, 1.08)); _fs = round(460 * _r.uniform(0.92, 1.06)); _halo = round(420 * _r.uniform(0.88, 1.07)); _dx = round(_r.uniform(-22, 22))
    
    _suby = min(_ring + 62, 950 - _cy)
    return scene(["var TITLE=" + json.dumps(str(title), ensure_ascii=False) + ";", "var SYM=" + json.dumps(str(symbol), ensure_ascii=False) + ";", "var SUB=" + json.dumps(str(sub), ensure_ascii=False) + ";", "var COL=" + json.dumps(col) + ";", "ctx.save();", "ctx.lineCap='round';ctx.lineJoin='round';", _TITLE_JS, "var cx=W/2+" + str(_dx) + ", cy=cursorY+" + str(_cy) + ";",
    
    "var e=EZ(CL(P*1.4));", "/* ── idle: float nhẹ cả cụm chính theo time (title đứng yên) ── */", "ctx.save();", "ctx.translate(0,3*Math.sin(time*0.8));", "/* ── quầng radial mờ sau lưng ── */", "if(e>0.01){", "  var g=ctx.createRadialGradient(cx,cy,40,cx,cy," + str(_halo) + ");", "  /* idle: quầng thở chậm theo time */", "  g.addColorStop(0,'rgba(255,255,255,'+((0.08+0.03*Math.sin(time*1.6))*e).toFixed(4)+')');", "  g.addColorStop(1,'rgba(255,255,255,0)');", "  ctx.fillStyle=g;", "  ctx.beginPath();ctx.arc(cx,cy," + str(_halo) + ",0,Math.PI*2);ctx.fill();", "}", "/* ── vòng nét đứt mảnh quay chậm, TỰ VẼ dần ── */", "if(e>0.003){", "  var rot=time*0.22;", "  ctx.globalAlpha=0.25;", "  ctx.strokeStyle='" + INK + "';ctx.lineWidth=2;", "  ctx.setLineDash([6,14]);", "  ctx.beginPath();ctx.arc(cx,cy," + str(_ring) + ",rot,rot+Math.PI*2*e);ctx.stroke();", "  ctx.setLineDash([]);", "  ctx.globalAlpha=1;", "}", "/* ── idle: chấm trắng nhỏ trôi chậm quanh vòng nét đứt ── */", "if(e>0.99){", "  var da=-Math.PI/2+time*0.5;", "  ctx.globalAlpha=0.7;",
    
    "  ctx.shadowColor='rgba(255,255,255,0.4)';ctx.shadowBlur=10;", "  ctx.fillStyle='#fff';", "  ctx.beginPath();ctx.arc(cx+" + str(_ring) + "*Math.cos(da),cy+" + str(_ring) + "*Math.sin(da),5,0,Math.PI*2);ctx.fill();", "  ctx.shadowBlur=0;ctx.globalAlpha=1;", "}", "/* ── symbol khổng lồ: scale 0.94→1 + clip ngang vẽ dần ── */", "var es=EZ(CL(P*1.2));", "if(es>0.003){", "  ctx.save();", "  var sc=0.94+0.06*es;", "  ctx.translate(cx,cy);ctx.scale(sc,sc);ctx.translate(-cx,-cy);", "  var fs=" + str(_fs) + ";",
    
    "  ctx.font='bold '+fs+'px Segoe UI, sans-serif';", "  var tw=ctx.measureText(SYM).width;", "  if(tw>W-160){fs=Math.floor(" + str(_fs) + "*(W-160)/tw);", "    ctx.font='bold '+fs+'px Segoe UI, sans-serif';", "    tw=ctx.measureText(SYM).width;}", "  /* clip ngang theo tiến độ (kiểu tự viết) */", "  ctx.beginPath();", "  ctx.rect(cx-tw/2-30,cy-fs*0.72,(tw+60)*es,fs*1.44);", "  ctx.clip();",
    
    "  ctx.textAlign='center';ctx.textBaseline='middle';", "  ctx.shadowColor='rgba(255,255,255,0.35)';ctx.shadowBlur=18;",
    
    "  ctx.fillStyle=COL;", "  ctx.fillText(SYM,cx,cy+10);", "  ctx.shadowBlur=0;", "  ctx.restore();", "}", "/* ── sub nhỏ muted dưới — reveal MUỘN giữa step (đồng hồ chậm P2) ── */", "if(SUB){", "  var eu=CL(P2*3-1.5);", "  ctx.globalAlpha=eu;", "  ctx.font='400 30px Segoe UI, sans-serif';ctx.fillStyle='" + MUTED + "';", "  ctx.textAlign='center';ctx.textBaseline='middle';", "  ctx.fillText(SUB,cx,cy+" + str(_suby) + "+10*(1-EZ(eu)));", "  ctx.globalAlpha=1;", "}", "ctx.restore();", "ctx.restore();"], 980)

_IFNS = ("parabola", "sin", "sqrt")
def mn_integral_area(title="", fn="parabola", a_label="a", b_label="b", formula="∫ f(x) dx", accent="blue", seed=0):
    fn = str(fn).lower()
    if fn not in _IFNS:
        fn = "parabola"
    ac = _acc(accent); acf = ACCENT_FILL.get(str(accent), ACCENT_FILL["blue"]); _r = _rng(seed); _vs = round(_r.uniform(0.84, 1.0), 3); _sh = round(_r.uniform(-30, 12), 1)
    
    _xw = round(_r.uniform(660, 738))
    
    _fa = round(_r.uniform(0.14, 0.32), 2)
    
    _fb = round(_r.uniform(0.7, 0.9), 2)
    
    _sfr = round(_r.uniform(5.0, 7.0), 2)
    
    _pe = round(_r.uniform(1.6, 2.8), 2)
    return scene(["var TITLE=" + json.dumps(str(title), ensure_ascii=False) + ";", "var FN=" + json.dumps(fn) + ";", "var AL=" + json.dumps(str(a_label), ensure_ascii=False) + ";", "var BL=" + json.dumps(str(b_label), ensure_ascii=False) + ";", "var FORM=" + json.dumps(str(formula), ensure_ascii=False) + ";", "var ACC=" + json.dumps(ac) + ";", "ctx.save();", "ctx.lineCap='round';ctx.lineJoin='round';ctx.textBaseline='middle';", _TITLE_JS, "var x0=170, x1=W-110, cy=cursorY+720;", "/* ── trục x/y mảnh vẽ dần + mũi tên ── */", "var ea=EZ(CL(P*1.8));", "if(ea>0){", "  ctx.strokeStyle='" + AXIS + "';ctx.lineWidth=2;", "  ctx.beginPath();ctx.moveTo(x0-30,cy);ctx.lineTo(x0-30+(x1-x0+30)*ea,cy);ctx.stroke();", "  ctx.beginPath();ctx.moveTo(x0,cy+26);ctx.lineTo(x0,cy+26-586*ea);ctx.stroke();", "}", "if(ea>0.96){", "  ctx.fillStyle='" + AXIS + "';", "  ctx.beginPath();ctx.moveTo(x1+10,cy);ctx.lineTo(x1-4,cy-6);ctx.lineTo(x1-4,cy+6);ctx.closePath();ctx.fill();", "  ctx.beginPath();ctx.moveTo(x0,cy-570);ctx.lineTo(x0-6,cy-556);ctx.lineTo(x0+6,cy-556);ctx.closePath();ctx.fill();", "}", "/* ── điểm đường cong theo fn ── */", "var n=140, PTS=[];", "for(var i=0;i<=n;i++){",
    
    "  var t=i/n, yv;", "  if(FN==='sin'){yv=300+200*Math.sin(t*" + str(_sfr) + "-0.8);}",
    
    "  else if(FN==='sqrt'){yv=80+420*Math.sqrt(t);}", "  else{yv=130+400*(1-Math.pow(Math.abs(2*t-1)," + str(_pe) + "));}", "  yv=yv*" + str(_vs) + "+" + str(_sh) + ";", "  PTS.push([200+t*" + str(_xw) + ",cy-yv]);",
    
    "}", "var ia=Math.round(n*" + str(_fa) + "), ib=Math.round(n*" + str(_fb) + ");", "var xa=PTS[ia][0], xb=PTS[ib][0];", "/* ── vùng tô QUÉT trái→phải (clip rect tăng dần, SAU đường cong) ── */", "var ef=EZ(CL(P*2.2-1.2));", "if(ef>0.003){", "  ctx.save();", "  ctx.beginPath();ctx.rect(xa,cy-620,(xb-xa)*ef,620);ctx.clip();", "  /* idle: vùng tô thở chậm theo time */", "  ctx.fillStyle='" + acf + "'+(0.13+0.03*Math.sin(time*1.6)).toFixed(3)+')';", "  ctx.beginPath();ctx.moveTo(xa,cy);", "  for(var j=ia;j<=ib;j++){ctx.lineTo(PTS[j][0],PTS[j][1]);}", "  ctx.lineTo(xb,cy);ctx.closePath();ctx.fill();", "  ctx.restore();", "}", "/* ── đường cong TỰ VẼ NÉT dần + chấm glow ở đầu ── */",
    
    "var ec=EZ(CL(P*1.4-0.15));", "var m=Math.floor(n*ec);", "if(m>0){", "  ctx.strokeStyle='" + INK + "';ctx.lineWidth=3;", "  ctx.beginPath();ctx.moveTo(PTS[0][0],PTS[0][1]);", "  for(var k=1;k<=m;k++){ctx.lineTo(PTS[k][0],PTS[k][1]);}", "  ctx.stroke();", "  if(ec>0.01&&ec<0.995){", "    ctx.shadowColor='rgba(255,255,255,0.35)';ctx.shadowBlur=8;", "    ctx.fillStyle='#fff';", "    ctx.beginPath();ctx.arc(PTS[m][0],PTS[m][1],7,0,Math.PI*2);ctx.fill();", "    ctx.shadowBlur=0;", "  }", "}", "/* ── idle: chấm trắng nhỏ trôi dọc đường cong khi đã vẽ xong ── */", "if(ec>=0.995){", "  var di=Math.max(0,Math.min(n,Math.round(((time*0.1)%1)*n)));", "  ctx.globalAlpha=0.65;", "  ctx.shadowColor='rgba(255,255,255,0.4)';ctx.shadowBlur=8;", "  ctx.fillStyle='#fff';", "  ctx.beginPath();ctx.arc(PTS[di][0],PTS[di][1],5,0,Math.PI*2);ctx.fill();", "  ctx.shadowBlur=0;ctx.globalAlpha=1;", "}", "/* ── 2 đường gióng đứng nét đứt tại a, b + nhãn — reveal MUỘN giữa step (P2) ── */", "var ed=CL(P2*3-1.5);", "if(ed>0){", "  ctx.globalAlpha=ed;",
    
    "  ctx.strokeStyle='" + DASH + "';ctx.lineWidth=2;", "  /* idle: nét đứt trôi chậm theo time */", "  ctx.setLineDash([8,8]);ctx.lineDashOffset=-time*8;", "  ctx.beginPath();ctx.moveTo(xa,cy);ctx.lineTo(xa,PTS[ia][1]);ctx.stroke();", "  ctx.beginPath();ctx.moveTo(xb,cy);ctx.lineTo(xb,PTS[ib][1]);ctx.stroke();", "  ctx.setLineDash([]);ctx.lineDashOffset=0;", "  ctx.font='400 30px Segoe UI, sans-serif';ctx.fillStyle='" + MUTED + "';", "  ctx.textAlign='center';", "  ctx.fillText(AL,xa,cy+42);", "  ctx.fillText(BL,xb,cy+42);", "  ctx.globalAlpha=1;", "}", "/* ── công thức 44px (ký hiệu ∫ to 56px) trên-phải — reveal MUỘN ~65% step (P2) ── */", "var efm=CL(P2*4-2.6);", "if(efm>0&&FORM){", "  ctx.globalAlpha=efm;", "  ctx.fillStyle='" + INK + "';ctx.textAlign='left';", "  var F44='400 44px Segoe UI, sans-serif';", "  var F56='400 56px Segoe UI, sans-serif';", "  var parts=FORM.split('\\u222b');", "  var tot=0, q;", "  for(q=0;q<parts.length;q++){", "    ctx.font=F44;tot+=ctx.measureText(parts[q]).width;", "    if(q<parts.length-1){ctx.font=F56;tot+=ctx.measureText('\\u222b').width;}", "  }", "  var fx=W-90-tot, fy=cursorY+250;", "  for(q=0;q<parts.length;q++){", "    ctx.font=F44;ctx.fillText(parts[q],fx,fy);", "    fx+=ctx.measureText(parts[q]).width;", "    if(q<parts.length-1){", "      ctx.font=F56;ctx.fillText('\\u222b',fx,fy);", "      fx+=ctx.measureText('\\u222b').width;", "    }", "  }", "  ctx.globalAlpha=1;", "}", "ctx.restore();"], 900)

def mn_venn(title="", left="Số chẵn", right="Chia hết 3", mid="6, 12, 18…", accent="yellow", seed=0):
    ac = _acc(accent); acf = ACCENT_FILL.get(str(accent), ACCENT_FILL["yellow"]); _r = _rng(seed); _R = round(260 * _r.uniform(0.85, 1.12)); _L = round(_r.uniform(110, 138)); _d = _R - _L; _dy = round(_r.uniform(-28, 30)); _lg = round(_r.uniform(38, 56))
    
    _lo = round(_R * 0.4); _wrap = 2 * _L - 10
    return scene(["var TITLE=" + json.dumps(str(title), ensure_ascii=False) + ";", "var LL=" + json.dumps(str(left), ensure_ascii=False) + ";", "var RL=" + json.dumps(str(right), ensure_ascii=False) + ";", "var MID=" + json.dumps(str(mid), ensure_ascii=False) + ";", "var ACC=" + json.dumps(ac) + ";", "ctx.save();", "ctx.lineCap='round';ctx.lineJoin='round';ctx.textBaseline='middle';", _TITLE_JS, "/* ── idle: float nhẹ cả cụm theo time (title đứng yên) ── */", "ctx.save();", "ctx.translate(0,3*Math.sin(time*0.8));", "var cy=cursorY+" + str(460 + _dy) + ", R=" + str(_R) + ";", "var cxL=W/2-" + str(_d) + ", cxR=W/2+" + str(_d) + ";", "/* ── vùng giao fill accent — reveal MUỘN ~40% step (P2) + pulse nhẹ ── */", "var ei=CL(P2*3-1.2);", "if(ei>0.003){", "  ctx.save();", "  ctx.beginPath();ctx.arc(cxL,cy,R,0,Math.PI*2);ctx.clip();", "  ctx.beginPath();ctx.arc(cxR,cy,R,0,Math.PI*2);ctx.clip();", "  var pu=0.14+0.03*Math.sin(time*1.8);", "  ctx.fillStyle='" + acf + "'+(pu*ei).toFixed(3)+')';", "  ctx.fillRect(cxL-R,cy-R,(cxR-cxL)+2*R,2*R);", "  ctx.restore();", "}", "/* ── 2 vòng tròn TỰ VẼ NÉT lần lượt + chấm glow ở đầu nét ── */", "var e1=EZ(CL(P*1.8));", "if(e1>0.003){", "  ctx.strokeStyle='" + INK + "';ctx.lineWidth=3;", "  ctx.beginPath();ctx.arc(cxL,cy,R,-Math.PI/2,-Math.PI/2+Math.PI*2*e1);ctx.stroke();", "  if(e1<0.995){", "    var a1=-Math.PI/2+Math.PI*2*e1;", "    ctx.shadowColor='rgba(255,255,255,0.35)';ctx.shadowBlur=8;", "    ctx.fillStyle='#fff';", "    ctx.beginPath();ctx.arc(cxL+R*Math.cos(a1),cy+R*Math.sin(a1),7,0,Math.PI*2);ctx.fill();", "    ctx.shadowBlur=0;", "  }", "}", "var e2=EZ(CL(P*1.8-0.8));", "if(e2>0.003){", "  ctx.strokeStyle='" + INK + "';ctx.lineWidth=3;", "  ctx.beginPath();ctx.arc(cxR,cy,R,Math.PI/2,Math.PI/2+Math.PI*2*e2);ctx.stroke();", "  if(e2<0.995){", "    var a2=Math.PI/2+Math.PI*2*e2;", "    ctx.shadowColor='rgba(255,255,255,0.35)';ctx.shadowBlur=8;", "    ctx.fillStyle='#fff';", "    ctx.beginPath();ctx.arc(cxR+R*Math.cos(a2),cy+R*Math.sin(a2),7,0,Math.PI*2);ctx.fill();", "    ctx.shadowBlur=0;", "  }", "}", "/* ── idle: 2 chấm trắng nhỏ trôi chậm ngược chiều quanh 2 vòng ── */", "if(e1>0.995){", "  var w1=-Math.PI/2+time*0.5;", "  ctx.globalAlpha=0.65;", "  ctx.shadowColor='rgba(255,255,255,0.4)';ctx.shadowBlur=8;", "  ctx.fillStyle='#fff';", "  ctx.beginPath();ctx.arc(cxL+R*Math.cos(w1),cy+R*Math.sin(w1),5,0,Math.PI*2);ctx.fill();", "  ctx.shadowBlur=0;ctx.globalAlpha=1;", "}",
    
    "if(e2>0.995){", "  var w2=Math.PI/2-time*0.5;", "  ctx.globalAlpha=0.65;", "  ctx.shadowColor='rgba(255,255,255,0.4)';ctx.shadowBlur=8;", "  ctx.fillStyle='#fff';", "  ctx.beginPath();ctx.arc(cxR+R*Math.cos(w2),cy+R*Math.sin(w2),5,0,Math.PI*2);ctx.fill();", "  ctx.shadowBlur=0;ctx.globalAlpha=1;", "}", "/* ── nhãn left/right ngoài mép mỗi vòng ── */", "var la=CL(P*1.8-0.6);", "if(la>0){", "  ctx.globalAlpha=la;", "  ctx.font='400 32px Segoe UI, sans-serif';ctx.fillStyle='" + MUTED + "';", "  ctx.textAlign='center';", "  ctx.fillText(LL,cxL-" + str(_lo) + ",cy-R-" + str(_lg) + ");", "  ctx.fillText(RL,cxR+" + str(_lo) + ",cy-R-" + str(_lg) + ");", "  ctx.globalAlpha=1;", "}", "/* ── mid trắng giữa vùng giao (wrap 2 dòng) — reveal MUỘN ~65% step (P2) ── */", "var em=CL(P2*4-2.6);", "if(em>0&&MID){", "  ctx.globalAlpha=em;", "  ctx.font='400 34px Segoe UI, sans-serif';ctx.fillStyle='" + INK + "';", "  ctx.textAlign='center';", "  var lines=wrapText(MID," + str(_wrap) + ",'400 34px Segoe UI, sans-serif').slice(0,2);", "  for(var li=0;li<lines.length;li++){", "    ctx.fillText(lines[li],W/2,cy+(li-(lines.length-1)/2)*46);", "  }", "  ctx.globalAlpha=1;", "}", "ctx.restore();", "ctx.restore();"], 820)

SCENES = {"mn_big_symbol": {"fn": mn_big_symbol, "doc": 'mn_big_symbol {"title":"","symbol":"π","sub":"tỉ số chu vi và đường kính","accent":false} — ký hiệu toán KHỔNG LỒ 460px giữa khung với quầng sáng radial + vòng nét đứt quay chậm; symbol hiện bằng clip ngang vẽ dần + scale; accent=true tô vàng', "demo": {"title": "Hằng số nổi tiếng nhất", "symbol": "π", "sub": "tỉ số chu vi và đường kính", "accent": False}}, "mn_integral_area": {"fn": mn_integral_area, "doc": 'mn_integral_area {"title":"","fn":"parabola","a_label":"a","b_label":"b","formula":"∫ f(x) dx","accent":"blue"} — trục + đường cong (parabola|sin|sqrt) tự vẽ nét dần, vùng dưới cong giữa a..b tô accent QUÉT trái→phải, gióng nét đứt tại a/b, công thức ∫ trên-phải', "demo": {"title": "Tích phân = diện tích dưới đường cong", "fn": "parabola", "a_label": "a", "b_label": "b", "formula": "∫ f(x) dx", "accent": "blue"}}, "mn_venn": {"fn": mn_venn, "doc": 'mn_venn {"title":"","left":"Số chẵn","right":"Chia hết 3","mid":"6, 12, 18…","accent":"yellow"} — 2 vòng tròn tự vẽ nét lần lượt giao nhau, vùng giao tô accent pulse nhẹ hiện sau cùng, nhãn 2 tập ngoài mép + phần tử chung trắng ở giữa', "demo": {"title": "Giao của hai tập hợp", "left": "Số chẵn", "right": "Chia hết 3", "mid": "6, 12, 18…", "accent": "yellow"}}}
