"""core/scenes_wp_2.py — Bộ scene warmpaper (phần 2): wp_timeline, wp_rules.

Phong cách "Mổ Xẻ Giấy Ấm": nền kem do renderer lo, scene TỰ CHỨA header
(chip tag màu + tiêu đề đen ấm #211a12 + dòng EN mono tuỳ chọn), card trắng
bo tròn bóng mềm, chấm timeline màu. Xem wp_spec.md.
"""
import json
from core.custom_scenes import scene; ACCENTS = {"orange": "#e8590c", "red": "#d9480f", "blue": "#1c7ed6", "green": "#2f9e44", "gray": "#adb5bd"}; INK = "#211a12"
def _hex_to_rgba(hx, a):
    hx = hx.lstrip("#"); b = int(hx[4:6], 16); g = int(hx[2:4], 16); r = int(hx[0:2], 16)
    return "rgba(%d,%d,%d,%s)" % (r, g, b, a)

_HELPERS_JS = "var ACC=" + json.dumps(ACCENTS) + ";function HA(hx,a){var h=hx.replace('#','');return 'rgba('+parseInt(h.substr(0,2),16)+','+parseInt(h.substr(2,2),16)+','+parseInt(h.substr(4,2),16)+','+a+')';}"
def _header_js(tag, title, en, ac):
    return [_HELPERS_JS, "var TAG=" + json.dumps(tag or "", ensure_ascii=False) + ";", "var TITLE=" + json.dumps(title or "", ensure_ascii=False) + ";", "var ENL=" + json.dumps(en or "", ensure_ascii=False) + ";", "var AC=" + json.dumps(ac) + ";", "ctx.save();ctx.textBaseline='middle';ctx.textAlign='center';", "/* chip tag */", "var hp=CL(P*2.2), hdy=16*(1-EZ(hp));", "if(TAG){", "  ctx.globalAlpha=Math.min(1,hp*1.6);", "  ctx.font='bold 30px Segoe UI, sans-serif';", "  var tgw=ctx.measureText(TAG).width+44;", "  ctx.fillStyle=HA(AC,0.12);RR(W/2-tgw/2,cursorY+hdy,tgw,56,10);ctx.fill();", "  ctx.strokeStyle=HA(AC,0.45);ctx.lineWidth=1.5;RR(W/2-tgw/2,cursorY+hdy,tgw,56,10);ctx.stroke();", "  ctx.fillStyle=AC;ctx.fillText(TAG,W/2,cursorY+hdy+29);", "}", "/* tieu de den am */", "var tp=CL(P*2.2-0.12), tdy=18*(1-EZ(tp));", "ctx.globalAlpha=Math.min(1,tp*1.6);", "var tf=64;ctx.font='bold '+tf+'px Segoe UI, sans-serif';", "while(ctx.measureText(TITLE).width>W-140&&tf>54){tf-=2;ctx.font='bold '+tf+'px Segoe UI, sans-serif';}", "var tls=[TITLE];", "if(ctx.measureText(TITLE).width>W-140){", "  tls=wrapText(TITLE,W-140,'bold '+tf+'px Segoe UI, sans-serif');", "  if(tls.length>2)tls=[tls[0],tls.slice(1).join(' ')];", "}", "ctx.fillStyle='#211a12';", "tls.forEach(function(ln,i){ctx.fillText(ln,W/2,cursorY+84+tdy+tf*0.55+i*(tf+8));});", "var tbot=cursorY+84+tls.length*(tf+8);", "/* dong EN mono xam */",
        
        "if(ENL){", "  var ep=CL(P*2.2-0.24);", "  ctx.globalAlpha=Math.min(1,ep*1.6);", "  ctx.font='bold 30px Consolas, monospace';ctx.fillStyle='#b0a08c';", "  ctx.fillText(ENL,W/2,tbot+(tls.length>1?18:28)+12*(1-EZ(ep)));", "}", "ctx.globalAlpha=1;ctx.restore();"]

def wp_timeline(tag="TIMELINE", color="orange", title="Dòng thời gian", en="", items=None):
    if not items:
        items = [{"date": "2026 · 04 · 04", "brand": "Anthropic", "head": "Chặn bên thứ ba", "sub": "130k agent đứt kết nối", "color": "red"},
            {"date": "2026 · 04 · 08", "brand": "Anthropic", "head": "Managed Agents", "sub": "trọn gói · closed runtime", "color": "orange"},
            {"date": "2026 · 04 · 15", "brand": "OpenAI", "head": "Agents SDK", "sub": "Harness mở · tự chọn cloud", "color": "blue"}]
    defaults = ["red", "orange", "blue", "green", "gray"]
    for i, it in enumerate(items):
        it.setdefault("color", defaults[i % len(defaults)])
    ac = ACCENTS.get(color, ACCENTS["orange"]); n = max(1, len(items)); height = 260 + n * 196
    return scene(_header_js(tag, title, en, ac) + ["var ITEMS=" + json.dumps(items, ensure_ascii=False) + ";", "var n=ITEMS.length;",
    
    "var DOTX=150, CX0=210, CW=W-80-210, CHH=170, PITCH=196;", "var y0=cursorY+260;", "ctx.save();ctx.textBaseline='middle';", "/* truc doc */", "var axTop=y0+55, axBot=y0+(n-1)*PITCH+CHH/2+30;", "var axp=EZ(CL(P*1.6));", "ctx.strokeStyle='#d7c8b4';ctx.lineWidth=3;", "ctx.beginPath();ctx.moveTo(DOTX,axTop);ctx.lineTo(DOTX,axTop+(axBot-axTop)*axp);ctx.stroke();", "ITEMS.forEach(function(it,i){", "  var rp=CL(P*2.2-0.22*i);if(rp<=0)return;", "  var e=EZ(rp), top=y0+i*PITCH+18*(1-e), cy=top+CHH/2;", "  var ic=ACC[it.color]||AC;", "  var on=(P*n>i+0.5);", "  var ga=Math.min(1,rp*1.5);", "  ctx.globalAlpha=ga;", "  /* card */", "  if(on){", "    ctx.shadowColor='rgba(160,110,60,0.18)';ctx.shadowBlur=18;ctx.shadowOffsetY=6;", "    ctx.fillStyle='rgba(255,255,255,0.92)';RR(CX0,top,CW,CHH,22);ctx.fill();", "    ctx.shadowBlur=0;ctx.shadowOffsetY=0;", "    ctx.fillStyle=HA(ic,0.10);RR(CX0,top,CW,CHH,22);ctx.fill();", "    ctx.strokeStyle=HA(ic,0.4);ctx.lineWidth=2;RR(CX0,top,CW,CHH,22);ctx.stroke();", "  }else{", "    ctx.fillStyle='rgba(255,255,255,0.45)';RR(CX0,top,CW,CHH,22);ctx.fill();", "    ctx.strokeStyle='rgba(160,110,60,0.18)';ctx.lineWidth=1.5;RR(CX0,top,CW,CHH,22);ctx.stroke();", "  }", "  /* cham timeline */", "  if(on){", "    ctx.strokeStyle=HA(ic,0.45);ctx.lineWidth=3;", "    ctx.beginPath();ctx.arc(DOTX,cy,16,0,Math.PI*2);ctx.stroke();", "    ctx.fillStyle=ic;ctx.beginPath();ctx.arc(DOTX,cy,9,0,Math.PI*2);ctx.fill();", "  }else{", "    ctx.strokeStyle='rgba(164,145,122,0.4)';ctx.lineWidth=3;", "    ctx.beginPath();ctx.arc(DOTX,cy,16,0,Math.PI*2);ctx.stroke();", "    ctx.fillStyle='#c4b5a0';ctx.beginPath();ctx.arc(DOTX,cy,9,0,Math.PI*2);ctx.fill();", "  }", "  /* chu trong card: mo khi chua active */", "  ctx.globalAlpha=ga*(on?1:0.35);", "  ctx.textAlign='left';", "  ctx.font='bold 30px Consolas, monospace';ctx.fillStyle=ic;", "  ctx.fillText(it.date||'',CX0+30,top+38);", "  ctx.textAlign='right';", "  ctx.font='24px Segoe UI, sans-serif';ctx.fillStyle='#8a7a66';", "  ctx.fillText(it.brand||'',CX0+CW-30,top+38);", "  ctx.textAlign='left';", "  var hf=44;ctx.font='bold '+hf+'px Segoe UI, sans-serif';", "  while(ctx.measureText(it.head||'').width>CW-60&&hf>30){hf-=2;ctx.font='bold '+hf+'px Segoe UI, sans-serif';}", "  ctx.fillStyle='#211a12';ctx.fillText(it.head||'',CX0+30,top+92);", "  var sf=26;ctx.font=sf+'px Segoe UI, sans-serif';", "  while(ctx.measureText(it.sub||'').width>CW-60&&sf>18){sf-=1;ctx.font=sf+'px Segoe UI, sans-serif';}", "  ctx.fillStyle='#8a7a66';ctx.fillText(it.sub||'',CX0+30,top+138);", "  ctx.globalAlpha=1;", "});", "ctx.restore();"], height)

def wp_rules(tag="ĐỘ TIN CẬY", color="green", title="Ba quy tắc cứng", items=None):
    if not items:
        items = [{"lead": "Khoá ngoài sandbox", "desc": "key nằm ở não, sandbox không thấy"},
            {"lead": "Đứt là nối tiếp", "desc": "sandbox chết, đổi máy chạy tiếp từ log"},
            {"lead": "Một kéo nhiều", "desc": "một não, nhiều tay cùng làm"}]
    ac = ACCENTS.get(color, ACCENTS["green"]); n = max(1, len(items)); height = 200 + n * 162
    return scene(_header_js(tag, title, "", ac) + ["var ITEMS=" + json.dumps(items, ensure_ascii=False) + ";", "var n=ITEMS.length;", "var RX=70, RW=W-140, RH=150, PITCH=162, y0=cursorY+190;", "/* hang active luan phien theo time, 2s/hang */", "var act=Math.floor(time/2)%n;", "ctx.save();ctx.textBaseline='middle';", "ITEMS.forEach(function(it,i){", "  var rp=CL(P*2.2-0.2*i);if(rp<=0)return;", "  var e=EZ(rp), top=y0+i*PITCH+20*(1-e);", "  var on=(i===act);", "  ctx.globalAlpha=Math.min(1,rp*1.5);", "  if(on){", "    ctx.fillStyle=HA(AC,0.10);RR(RX,top,RW,RH,18);ctx.fill();", "    ctx.strokeStyle=HA(AC,0.35);ctx.lineWidth=1.5;RR(RX,top,RW,RH,18);ctx.stroke();", "  }", "  /* so thu tu */", "  ctx.textAlign='left';", "  ctx.font='bold 40px Consolas, monospace';", "  ctx.fillStyle=on?AC:'#c4b5a0';", "  ctx.fillText('0'+(i+1),RX+36,top+RH/2);", "  /* lead in dam + ' · ' + desc xam, wrap toi da 2 dong */", "  var tx=RX+128, maxw=RW-128-34;", "  var lead=it.lead||'', desc=it.desc||'';", "  var lf=34;ctx.font='bold '+lf+'px Segoe UI, sans-serif';", "  while(ctx.measureText(lead).width>maxw-140&&lf>26){lf-=1;ctx.font='bold '+lf+'px Segoe UI, sans-serif';}", "  var lw1=ctx.measureText(lead).width;", "  ctx.font='30px Segoe UI, sans-serif';",
    
    "  var sep=' · ', sw=ctx.measureText(sep).width;", "  var a1=maxw-lw1-sw, l1='', l2='';", "  desc.split(' ').forEach(function(wd){", "    var t=l1?l1+' '+wd:wd;",
    
    "    if(!l2&&ctx.measureText(t).width<=a1){l1=t;}", "    else{l2=l2?l2+' '+wd:wd;}", "  });",
    
    "  /* can bang 2 dong: tranh dong 2 chi con 1 tu le loi */", "  if(l2){", "    var ws=l1.split(' ');", "    while(ws.length>1&&ctx.measureText(l2).width<ctx.measureText(ws.join(' ')).width*0.45){", "      var mv=ws.pop();", "      if(ctx.measureText(mv+' '+l2).width>maxw){ws.push(mv);break;}", "      l2=mv+' '+l2;l1=ws.join(' ');", "    }", "  }", "  while(ctx.measureText(l2).width>maxw&&l2.length>2){l2=l2.slice(0,-2)+'…';}", "  var two=(l2!=='');", "  var y1=top+RH/2-(two?24:0), y2=top+RH/2+28;", "  ctx.font='bold '+lf+'px Segoe UI, sans-serif';ctx.fillStyle='#211a12';", "  ctx.fillText(lead,tx,y1);", "  ctx.font='30px Segoe UI, sans-serif';ctx.fillStyle='#6f6152';", "  ctx.fillText(sep+l1,tx+lw1,y1+2);", "  if(two)ctx.fillText(l2,tx,y2);", "  ctx.globalAlpha=1;", "});", "ctx.restore();"], height)

SCENES = {"wp_timeline": {"fn": wp_timeline, "doc": 'wp_timeline {"tag":"TIMELINE · 11 NGÀY","color":"orange","title":"Sao tự dưng mở?","en":"WHO FORCED IT · 11 DAYS","items":[{"date":"2026 · 04 · 04","brand":"Anthropic","head":"Chặn bên thứ ba","sub":"130k agent đứt kết nối","color":"red"}]} — timeline dọc chấm màu, item sáng dần lần lượt theo tiến độ (active: chấm màu + card nền màu nhạt)', "demo": {"tag": "TIMELINE · 11 NGÀY", "color": "orange", "title": "Sao tự dưng mở?", "en": "WHO FORCED IT · 11 DAYS", "items": [{"date": "2026 · 04 · 04", "brand": "Anthropic", "head": "Chặn bên thứ ba", "sub": "130k agent đứt kết nối", "color": "red"},
    {"date": "2026 · 04 · 08", "brand": "Anthropic", "head": "Managed Agents", "sub": "trọn gói · closed runtime", "color": "orange"},
    {"date": "2026 · 04 · 15", "brand": "OpenAI", "head": "Agents SDK", "sub": "Harness mở · tự chọn cloud", "color": "blue"}]}}, "wp_rules": {"fn": wp_rules, "doc": 'wp_rules {"tag":"ĐỘ TIN CẬY","color":"green","title":"Ba quy tắc cứng","items":[{"lead":"Khoá ngoài sandbox","desc":"key nằm ở não, sandbox không thấy"}]} — danh sách quy tắc đánh số 01/02/03, hàng active luân phiên theo thời gian (nền accent nhạt)', "demo": {"tag": "ĐỘ TIN CẬY", "color": "green", "title": "Ba quy tắc cứng", "items": [{"lead": "Khoá ngoài sandbox", "desc": "key nằm ở não, sandbox không thấy"},
    {"lead": "Đứt là nối tiếp", "desc": "sandbox chết, đổi máy chạy tiếp từ log"},
    {"lead": "Một kéo nhiều", "desc": "một não, nhiều tay cùng làm"}]}}}
