"""core/scenes_td_4.py — Bộ scene techdark #4: td_state_board, td_versus_cross, td_step_chain.

Phong cách "Mổ Xẻ Công Nghệ": nền than chì do renderer lo, linh kiện viền mảnh
màu theo section, tag chip mono nhỏ, chữ trắng đậm. Xem td_spec.md.
"""
import json
from core.custom_scenes import scene; _TD = "var AC={cyan:'#22d3ee',green:'#34d399',orange:'#fb923c',yellow:'#fbbf24',red:'#f87171',purple:'#a78bfa',blue:'#38bdf8'};var TXT='#f5f7f9',MUT='#9aa3ad',CARD='rgba(16,21,26,0.85)';function HA(h,a){return 'rgba('+parseInt(h.slice(1,3),16)+','+parseInt(h.slice(3,5),16)+','+parseInt(h.slice(5,7),16)+','+a+')';}"
def td_state_board(steps=None, active=2, board_title="Cùng MỘT trạng thái tác vụ", board_sub="được cập nhật sau mỗi vòng", limits=None, limits_title="cả chuỗi đều bị ràng buộc", color="green"):
    if not steps:
        steps = [{"icon": "📥", "label": "Nhận thông tin"},
            {"icon": "🧭", "label": "Định bước kế"},
            {"icon": "🛠", "label": "Gọi công cụ"},
            {"icon": "📤", "label": "Lấy kết quả"},
            {"icon": "➡", "label": "Tiến tiếp"}]
    if not limits:
        limits = [{"label": "Quyền", "color": "red"},
            {"label": "Ngân sách", "color": "yellow"},
            {"label": "Cửa sổ ngữ cảnh", "color": "blue"},
            {"label": "Tính liên tục", "color": "purple"}]
    return scene([_TD, "var STEPS=" + json.dumps(steps, ensure_ascii=False) + ";", "var LIMITS=" + json.dumps(limits, ensure_ascii=False) + ";", "var ACT=" + str(int(active)) + ";", "var TITLE=" + json.dumps(board_title, ensure_ascii=False) + ";", "var SUB=" + json.dumps(board_sub, ensure_ascii=False) + ";",
    
    "var LTITLE=" + json.dumps(limits_title, ensure_ascii=False) + ";", "var y0=cursorY;", "var rowCols=['cyan','yellow','green','orange','purple'];", "ctx.save();", "/* ── giữa: panel trạng thái 460x420 ── */", "var px=310,pw=460,py=y0+50,ph=420;", "var pp=CL(P*1.6);", "ctx.globalAlpha=pp;", "ctx.fillStyle='rgba(10,14,18,0.9)';RR(px,py,pw,ph,14);ctx.fill();", "ctx.strokeStyle='rgba(255,255,255,0.12)';ctx.lineWidth=1.5;RR(px,py,pw,ph,14);ctx.stroke();", "ctx.textAlign='center';ctx.textBaseline='middle';", "ctx.fillStyle=TXT;ctx.font='bold 26px Segoe UI, sans-serif';", "ctx.fillText(TITLE,px+pw/2,py+52);", "ctx.fillStyle=AC.cyan;ctx.font='22px Segoe UI, sans-serif';", "ctx.fillText(SUB,px+pw/2,py+88);", "var bl=pw-130;", "STEPS.forEach(function(s,i){", "  var rp=CL(P*2.2-0.3-i*0.15);if(rp<=0)return;", "  var ry=py+142+i*56;", "  var isA=(i===ACT);", "  var col=isA?AC.green:AC[rowCols[i%5]];", "  ctx.globalAlpha=pp*rp;", "  ctx.strokeStyle='rgba(255,255,255,0.10)';ctx.lineWidth=5;ctx.lineCap='round';", "  ctx.beginPath();ctx.moveTo(px+36,ry);ctx.lineTo(px+36+bl,ry);ctx.stroke();", "  var frac=isA?EZ(rp):EZ(rp)*(0.32+0.3*(0.5+0.5*Math.sin(time*0.9+i*1.4)));", "  ctx.strokeStyle=isA?AC.green:HA(col,0.55);", "  if(isA){ctx.shadowColor=AC.green;ctx.shadowBlur=10;}", "  ctx.beginPath();ctx.moveTo(px+36,ry);ctx.lineTo(px+36+bl*frac,ry);ctx.stroke();", "  ctx.shadowBlur=0;", "  /* chấm tròn cuối thanh */", "  if(isA){", "    ctx.fillStyle=AC.green;ctx.shadowColor=AC.green;ctx.shadowBlur=12;", "    ctx.beginPath();ctx.arc(px+36+bl+26,ry,11,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;", "    ctx.fillStyle='#0b0f13';ctx.font='bold 15px Segoe UI, sans-serif';", "    ctx.fillText('\\u2713',px+36+bl+26,ry+1);", "  }else{", "    ctx.strokeStyle=HA(col,0.5);ctx.lineWidth=2;", "    ctx.beginPath();ctx.arc(px+36+bl+26,ry,8,0,Math.PI*2);ctx.stroke();", "  }",
    
    "});", "ctx.globalAlpha=1;", "/* ── trái: 5 hàng icon + label ── */", "var lx=60,ly=y0+82,rh=78;", "STEPS.forEach(function(s,i){", "  var p=CL(P*2-i*0.14);if(p<=0)return;",
    
    "  var e=EZ(p),yy=ly+i*rh+16*(1-e);", "  var isA=(i===ACT);", "  var col=isA?AC.green:AC[rowCols[i%5]];", "  ctx.globalAlpha=p;", "  if(isA){", "    ctx.setLineDash([6,5]);ctx.lineDashOffset=-time*18;", "    ctx.strokeStyle=HA(AC.green,0.75);ctx.lineWidth=1.5;", "    ctx.shadowColor=AC.green;ctx.shadowBlur=10;",
    
    "    RR(lx-8,yy-11,244,58,12);ctx.stroke();", "    ctx.shadowBlur=0;ctx.setLineDash([]);", "  }", "  ctx.fillStyle=CARD;RR(lx,yy,36,36,9);ctx.fill();", "  ctx.strokeStyle=HA(col,isA?0.95:0.55);ctx.lineWidth=1.5;RR(lx,yy,36,36,9);ctx.stroke();", "  ctx.font='21px Segoe UI, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';", "  ctx.fillText(s.icon,lx+18,yy+19);", "  ctx.textAlign='left';", "  ctx.fillStyle=isA?AC.green:TXT;", "  ctx.font=(isA?'bold ':'')+'26px Segoe UI, sans-serif';", "  var lb=s.label;", "  while(ctx.measureText(lb).width>178&&lb.length>4){lb=lb.slice(0,-2);}", "  ctx.fillText(lb,lx+50,yy+19);", "  ctx.globalAlpha=1;", "});", "/* ── phải: card giới hạn ── */", "var qx=790,qw=230;", "var qp=CL(P*1.8-0.5);", "ctx.globalAlpha=qp;", "ctx.textAlign='left';ctx.textBaseline='middle';", "ctx.fillStyle=MUT;ctx.font='20px Segoe UI, sans-serif';", "wrapText(LTITLE,qw-8,'20px Segoe UI').slice(0,2).forEach(function(l,i){", "  ctx.fillText(l,qx+6,y0+66+i*26);", "});", "var qy=y0+122,qh=LIMITS.length*56+26;", "ctx.fillStyle=CARD;RR(qx,qy,qw,qh,14);ctx.fill();", "ctx.strokeStyle='rgba(255,255,255,0.15)';ctx.lineWidth=1.5;RR(qx,qy,qw,qh,14);ctx.stroke();", "LIMITS.forEach(function(it,i){", "  var p=CL(P*2-0.7-i*0.15);if(p<=0)return;", "  var ry=qy+42+i*56;", "  var col=AC[it.color]||AC.cyan;", "  ctx.globalAlpha=qp*p;", "  /* nối chấm sang panel bằng nét mảnh */", "  ctx.strokeStyle=HA(col,0.42);ctx.lineWidth=1.2;", "  ctx.beginPath();ctx.moveTo(qx-2,ry);ctx.lineTo(px+pw+2,py+142+Math.min(i,4)*56);ctx.stroke();", "  ctx.fillStyle=col;ctx.shadowColor=col;ctx.shadowBlur=8;", "  ctx.beginPath();ctx.arc(qx+24,ry,7,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;", "  ctx.fillStyle=TXT;", "  var f=24;ctx.font=f+'px Segoe UI, sans-serif';", "  while(ctx.measureText(it.label).width>qw-62&&f>18){f-=1;ctx.font=f+'px Segoe UI, sans-serif';}", "  ctx.fillText(it.label,qx+44,ry);", "});", "ctx.globalAlpha=1;ctx.restore();"], 520)

def td_versus_cross(wrong_title="Đừng dừng ở bề mặt", wrongs=None, right_title="Đi vào tầng tác vụ", right_head="Làm xong việc theo từng vòng", rights=None, color="green"):
    if not wrongs:
        wrongs = ["Chat vài câu cho vui", "Chỉ học prompt", "Hỏi câu thật đẹp"]
    if not rights:
        rights = ["Nhận thông tin → định bước", "Gọi tool → lấy kết quả", "Tiến tiếp → làm thật"]
    return scene([_TD, "var WRONGS=" + json.dumps(wrongs, ensure_ascii=False) + ";", "var RIGHTS=" + json.dumps(rights, ensure_ascii=False) + ";", "var WT=" + json.dumps(wrong_title, ensure_ascii=False) + ";", "var RT=" + json.dumps(right_title, ensure_ascii=False) + ";", "var RH=" + json.dumps(right_head, ensure_ascii=False) + ";", "var ACC=AC[" + json.dumps(color) + "]||AC.green;",
    
    "var y0=cursorY;", "var strikeCols=[AC.red,AC.yellow,AC.orange];", "ctx.save();", "/* ── trái: card cách cũ ── */", "var lx=60,lw=420,ly=y0+10,lh=430;", "var lp=CL(P*1.8);", "ctx.globalAlpha=lp;", "ctx.fillStyle=CARD;RR(lx,ly,lw,lh,14);ctx.fill();", "ctx.strokeStyle='rgba(255,255,255,0.15)';ctx.lineWidth=1.5;RR(lx,ly,lw,lh,14);ctx.stroke();", "ctx.textAlign='left';ctx.textBaseline='middle';", "ctx.fillStyle=MUT;ctx.font='bold 22px Consolas, monospace';", "ctx.fillText(WT,lx+24,ly+40);", "WRONGS.forEach(function(t,i){", "  var p=CL(P*2-0.25-i*0.22);if(p<=0)return;", "  var e=EZ(p);", "  var bx=lx+22,by=ly+76+i*114+14*(1-e),bw=lw-44,bh=90;", "  ctx.globalAlpha=lp*p;", "  ctx.fillStyle='rgba(255,255,255,0.03)';RR(bx,by,bw,bh,12);ctx.fill();", "  ctx.strokeStyle='rgba(255,255,255,0.15)';ctx.lineWidth=1.5;RR(bx,by,bw,bh,12);ctx.stroke();", "  ctx.fillStyle=MUT;", "  var f=26;ctx.font=f+'px Segoe UI, sans-serif';", "  while(ctx.measureText(t).width>bw-40&&f>20){f-=1;ctx.font=f+'px Segoe UI, sans-serif';}", "  ctx.fillText(t,bx+22,by+bh/2);", "  /* đường gạch chéo vẽ dần theo P */", "  var sp=CL(P*2-0.55-i*0.28);", "  if(sp>0){", "    var se=EZ(sp);", "    ctx.strokeStyle=strikeCols[i%3];ctx.lineWidth=5;ctx.lineCap='round';", "    ctx.shadowColor=strikeCols[i%3];ctx.shadowBlur=12;", "    ctx.beginPath();ctx.moveTo(bx+16,by+bh/2+11);", "    ctx.lineTo(bx+16+(bw-32)*se,by+bh/2+11-22*se);ctx.stroke();", "    ctx.shadowBlur=0;", "  }", "  ctx.globalAlpha=1;", "});", "/* ── mũi tên nét đứt ở giữa ── */", "var ap=CL(P*2-0.8);", "if(ap>0){", "  var my=y0+225;", "  ctx.globalAlpha=ap;", "  ctx.strokeStyle=AC.green;ctx.lineWidth=4;ctx.lineCap='round';", "  ctx.setLineDash([8,6]);ctx.lineDashOffset=-time*30;", "  ctx.shadowColor=AC.green;ctx.shadowBlur=10;", "  ctx.beginPath();ctx.moveTo(lx+lw+10,my);ctx.lineTo(lx+lw+58,my);ctx.stroke();", "  ctx.setLineDash([]);", "  ctx.fillStyle=AC.green;", "  ctx.beginPath();ctx.moveTo(lx+lw+72,my);ctx.lineTo(lx+lw+54,my-11);", "  ctx.lineTo(lx+lw+54,my+11);ctx.closePath();ctx.fill();", "  ctx.shadowBlur=0;ctx.globalAlpha=1;", "}", "/* ── phải: card cách đúng ── */", "var rx=560,rw=460,ry=y0+10,rh=430;", "var rp0=CL(P*1.8-0.35);",
    
    "ctx.globalAlpha=rp0;", "ctx.fillStyle=CARD;RR(rx,ry,rw,rh,14);ctx.fill();", "ctx.strokeStyle=HA(ACC,0.55);ctx.lineWidth=1.5;RR(rx,ry,rw,rh,14);ctx.stroke();", "ctx.fillStyle=ACC;ctx.font='bold 22px Consolas, monospace';", "ctx.fillText(RT,rx+24,ry+40);", "ctx.fillStyle=TXT;ctx.font='bold 34px Segoe UI, sans-serif';", "var hls=wrapText(RH,rw-48,'bold 34px Segoe UI').slice(0,2);", "hls.forEach(function(l,i){ctx.fillText(l,rx+24,ry+96+i*44);});", "var ryy=ry+96+hls.length*44+38;", "RIGHTS.forEach(function(t,i){", "  var p=CL(P*2-0.7-i*0.22);if(p<=0)return;", "  var e=EZ(p),xx=rx+24+18*(1-e),yy=ryy+i*76;", "  ctx.globalAlpha=rp0*p;", "  ctx.fillStyle=AC.green;ctx.shadowColor=AC.green;ctx.shadowBlur=8;", "  ctx.beginPath();ctx.arc(xx+8,yy,7,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;", "  ctx.fillStyle=TXT;", "  var f=26;ctx.font=f+'px Segoe UI, sans-serif';", "  while(ctx.measureText(t).width>rw-78&&f>20){f-=1;ctx.font=f+'px Segoe UI, sans-serif';}", "  ctx.fillText(t,xx+30,yy);", "  ctx.globalAlpha=1;", "});", "ctx.restore();"], 460)

def td_step_chain(steps=None, note="Kết quả tool không phải file đính kèm — nó quay lại vòng sau", color="cyan"):
    if not steps:
        steps = [{"tag": "Bước 1", "label": "Đánh giá vòng kế", "color": "purple"},
            {"tag": "Bước 2", "label": "Phát yêu cầu tool", "color": "cyan"},
            {"tag": "Bước 3", "label": "Hệ thống thực thi", "color": "yellow"},
            {"tag": "Bước 4", "label": "Trả kết quả về", "color": "green"}]
    return scene([_TD, "var STEPS=" + json.dumps(steps, ensure_ascii=False) + ";", "var NOTE=" + json.dumps(note, ensure_ascii=False) + ";", "var y0=cursorY,n=STEPS.length;", "var gap=46,tw=W-120,cw=(tw-gap*(n-1))/n,chh=152,cy0=y0+14;", "ctx.save();ctx.textBaseline='middle';", "STEPS.forEach(function(s,i){", "  var p=CL(P*2-i*0.22);if(p<=0)return;", "  var e=EZ(p);", "  var cx=60+i*(cw+gap),yy=cy0+16*(1-e);", "  var col=AC[s.color]||AC.cyan;", "  var isG=(i===1);", "  ctx.globalAlpha=p;", "  if(isG){ctx.shadowColor=col;ctx.shadowBlur=14;}", "  ctx.fillStyle=CARD;RR(cx,yy,cw,chh,14);ctx.fill();ctx.shadowBlur=0;", "  ctx.strokeStyle=HA(col,isG?0.9:0.55);ctx.lineWidth=1.5;RR(cx,yy,cw,chh,14);ctx.stroke();", "  ctx.textAlign='left';", "  ctx.fillStyle=col;ctx.font='bold 22px Consolas, monospace';", "  ctx.fillText(s.tag,cx+24,yy+34);", "  ctx.fillStyle=TXT;", "  var f=26,ls=wrapText(s.label,cw-40,'bold 26px Segoe UI');", "  if(ls.length>2){f=23;ls=wrapText(s.label,cw-40,'bold 23px Segoe UI');}", "  ctx.font='bold '+f+'px Segoe UI, sans-serif';", "  ls.slice(0,2).forEach(function(l,j){ctx.fillText(l,cx+24,yy+76+j*34);});", "  /* mũi tên đặc giữa các card */", "  if(i<n-1){", "    var ap=CL(P*2-0.2-i*0.22);", "    if(ap>0){", "      var my=cy0+chh/2,ax0=cx+cw+9,ax1=cx+cw+gap-9;", "      ctx.globalAlpha=ap;", "      ctx.strokeStyle='rgba(245,247,249,'+(0.3+0.6*ap)+')';", "      ctx.lineWidth=4;ctx.lineCap='round';", "      ctx.beginPath();ctx.moveTo(ax0,my);ctx.lineTo(ax1-10,my);ctx.stroke();", "      ctx.fillStyle='rgba(245,247,249,'+(0.3+0.6*ap)+')';", "      ctx.beginPath();ctx.moveTo(ax1,my);ctx.lineTo(ax1-14,my-9);", "      ctx.lineTo(ax1-14,my+9);ctx.closePath();ctx.fill();", "    }", "  }", "  ctx.globalAlpha=1;", "});", "/* pill chú thích giữa dưới */", "var np=CL(P*2-1.0);", "if(np>0){", "  ctx.globalAlpha=np;", "  var f2=26;ctx.font=f2+'px Segoe UI, sans-serif';", "  while(ctx.measureText(NOTE).width>tw-70&&f2>19){f2-=1;ctx.font=f2+'px Segoe UI, sans-serif';}", "  var mw=ctx.measureText(NOTE).width+64;",
    
    "  var pyy=cy0+chh+52,phh=58;", "  ctx.fillStyle=CARD;RR(W/2-mw/2,pyy,mw,phh,29);ctx.fill();", "  ctx.strokeStyle='rgba(255,255,255,0.15)';ctx.lineWidth=1.5;RR(W/2-mw/2,pyy,mw,phh,29);ctx.stroke();", "  ctx.fillStyle=TXT;ctx.textAlign='center';",
    
    "  ctx.fillText(NOTE,W/2,pyy+phh/2+1);", "  ctx.globalAlpha=1;", "}", "ctx.restore();"], 330)

SCENES = {"td_state_board": {"fn": td_state_board, "doc": 'td_state_board {"steps":[{"icon":"📥","label":"Nhận thông tin"},...5],"active":2,"board_title":"...","board_sub":"...","limits":[{"label":"Quyền","color":"red"},...4],"limits_title":"..."} — bảng trạng thái tác vụ 3 cột: trái 5 bước icon, giữa panel progress, phải các ràng buộc nối dây sang panel', "demo": {"steps": [{"icon": "📥", "label": "Nhận thông tin"},
    {"icon": "🧭", "label": "Định bước kế"},
    {"icon": "🛠", "label": "Gọi công cụ"},
    {"icon": "📤", "label": "Lấy kết quả"},
    {"icon": "➡", "label": "Tiến tiếp"}], "active": 2, "board_title": "Cùng MỘT trạng thái tác vụ", "board_sub": "được cập nhật sau mỗi vòng", "limits": [{"label": "Quyền", "color": "red"},
    {"label": "Ngân sách", "color": "yellow"},
    {"label": "Cửa sổ ngữ cảnh", "color": "blue"},
    {"label": "Tính liên tục", "color": "purple"}], "limits_title": "cả chuỗi đều bị ràng buộc"}}, "td_versus_cross": {"fn": td_versus_cross, "doc": 'td_versus_cross {"wrong_title":"...","wrongs":["..."x3],"right_title":"...","right_head":"...","rights":["..."x3],"color":"green"} — trái: các cách cũ bị gạch chéo màu; mũi tên nét đứt green; phải: card cách đúng với đầu dòng chấm green', "demo": {"wrong_title": "Đừng dừng ở bề mặt", "wrongs": ["Chat vài câu cho vui", "Chỉ học prompt", "Hỏi câu thật đẹp"], "right_title": "Đi vào tầng tác vụ", "right_head": "Làm xong việc theo từng vòng", "rights": ["Nhận thông tin → định bước", "Gọi tool → lấy kết quả", "Tiến tiếp → làm thật"], "color": "green"}}, "td_step_chain": {"fn": td_step_chain, "doc": 'td_step_chain {"steps":[{"tag":"Bước 1","label":"...","color":"purple"},...4],"note":"..."} — chuỗi 4 card bước ngang nối mũi tên đặc, card 2 glow active, pill chú thích ở dưới', "demo": {"steps": [{"tag": "Bước 1", "label": "Đánh giá vòng kế", "color": "purple"},
    {"tag": "Bước 2", "label": "Phát yêu cầu tool", "color": "cyan"},
    {"tag": "Bước 3", "label": "Hệ thống thực thi", "color": "yellow"},
    {"tag": "Bước 4", "label": "Trả kết quả về", "color": "green"}], "note": "Kết quả tool không phải file đính kèm — nó quay lại vòng sau"}}}
