"""core/scenes_td_3.py — Bộ scene techdark (nhóm 3): td_shield, td_sandbox,
td_context_gauge. Phong cách video giải thích công nghệ premium: nền than chì
(renderer lo), linh kiện viền mảnh màu theo section, tag chip nhỏ, chữ trắng đậm.
"""
import json
from core.custom_scenes import scene; ACCENT = {"cyan": "#22d3ee", "green": "#34d399", "orange": "#fb923c", "yellow": "#fbbf24", "red": "#f87171", "purple": "#a78bfa", "blue": "#38bdf8"}; TXT = "#f5f7f9"; MUTED = "#9aa3ad"; CARD = "rgba(16,21,26,0.85)"; QP = "function QP(t,x0,y0,qx,qy,x1,y1){var u=1-t;return[u*u*x0+2*u*t*qx+t*t*x1,u*u*y0+2*u*t*qy+t*t*y1];}"
def td_shield(input="Yêu cầu hành động", policy="Chính sách quyền", allow="Được làm ngay", confirm="Phải hỏi bạn", deny="Không được làm"):
    rows = json.dumps([[allow, ACCENT["green"], "check"], [confirm, ACCENT["yellow"], "dot"], [deny, ACCENT["red"], "x"]], ensure_ascii=False)
    return scene([QP, "var INP=" + json.dumps(input, ensure_ascii=False) + ";", "var POL=" + json.dumps(policy, ensure_ascii=False) + ";", "var ROWS=" + rows + ";", "var top=cursorY;", "ctx.save();ctx.textBaseline='middle';", "/* card trái: yêu cầu vào */", "var a1=EZ(CL(P*2));", "var lcx=60,lcy=top+170,lcw=200,lch=150,ls=(1-a1)*18;", "if(a1>0){", "ctx.globalAlpha=a1;", "ctx.fillStyle='rgba(16,21,26,0.85)';RR(lcx,lcy+ls,lcw,lch,14);ctx.fill();", "ctx.strokeStyle='rgba(255,255,255,0.18)';ctx.lineWidth=1.5;RR(lcx,lcy+ls,lcw,lch,14);ctx.stroke();", "ctx.textAlign='center';ctx.font='36px Segoe UI, sans-serif';", "ctx.fillText('\\ud83d\\udcc4',lcx+lcw/2,lcy+ls+44);", "ctx.fillStyle='#f5f7f9';ctx.font='24px Segoe UI, sans-serif';", "wrapText(INP,lcw-28,'24px Segoe UI, sans-serif').slice(0,2).forEach(function(l,i){", "  ctx.fillText(l,lcx+lcw/2,lcy+ls+94+i*30);});", "ctx.globalAlpha=1;}", "/* khiên đỏ ở giữa */", "var a2=EZ(CL(P*2-0.25));", "var sx=440,sy=top+245;", "if(a2>0){", "ctx.globalAlpha=a2;", "ctx.strokeStyle='rgba(255,255,255,0.35)';ctx.lineWidth=2;", "ctx.setLineDash([8,6]);ctx.lineDashOffset=-time*30;", "ctx.beginPath();ctx.moveTo(lcx+lcw+10,sy);ctx.lineTo(sx-96,sy);ctx.stroke();ctx.setLineDash([]);", "ctx.fillStyle='rgba(255,255,255,0.5)';", "ctx.beginPath();ctx.moveTo(sx-86,sy);ctx.lineTo(sx-98,sy-6);ctx.lineTo(sx-98,sy+6);ctx.closePath();ctx.fill();", "var pg=10+6*Math.sin(time*2.6);",
    
    "ctx.save();ctx.translate(sx,sy);ctx.scale(a2,a2);ctx.translate(-sx,-sy);", "ctx.beginPath();ctx.moveTo(sx,sy-85);", "ctx.quadraticCurveTo(sx+78,sy-78,sx+75,sy-38);", "ctx.quadraticCurveTo(sx+72,sy+42,sx,sy+85);",
    
    "ctx.quadraticCurveTo(sx-72,sy+42,sx-75,sy-38);", "ctx.quadraticCurveTo(sx-78,sy-78,sx,sy-85);ctx.closePath();", "ctx.fillStyle='rgba(16,21,26,0.9)';ctx.fill();", "ctx.strokeStyle='#f87171';ctx.lineWidth=4;", "ctx.shadowColor='#f87171';ctx.shadowBlur=pg;ctx.stroke();ctx.shadowBlur=0;", "ctx.lineWidth=3;", "ctx.beginPath();ctx.arc(sx,sy-8,24,0,Math.PI*2);ctx.stroke();", "ctx.beginPath();ctx.moveTo(sx-11,sy-8);ctx.lineTo(sx+11,sy-8);", "ctx.moveTo(sx,sy-19);ctx.lineTo(sx,sy+3);ctx.stroke();", "ctx.restore();", "ctx.fillStyle='#9aa3ad';ctx.font='26px Segoe UI, sans-serif';ctx.textAlign='center';", "wrapText(POL,280,'26px Segoe UI, sans-serif').slice(0,2).forEach(function(l,i){", "  ctx.fillText(l,sx,sy+122+i*32);});", "ctx.globalAlpha=1;}",
    
    "/* tiêu đề nhỏ trên 3 nhánh */", "var a3=CL(P*2-0.45);", "if(a3>0){ctx.globalAlpha=a3;ctx.fillStyle='#9aa3ad';", "ctx.font='22px Consolas, monospace';ctx.textAlign='center';", "ctx.fillText('ranh giới thực thi',830,top+52);ctx.globalAlpha=1;}", "/* 3 nhánh kết quả bên phải */", "ROWS.forEach(function(r,i){", "  var ra=EZ(CL(P*2-0.55-i*0.2));if(ra<=0)return;", "  var ry=top+130+i*125,rx=640;", "  ctx.globalAlpha=ra*0.8;ctx.strokeStyle=r[1];ctx.lineWidth=2;", "  if(r[2]==='x'){ctx.setLineDash([9,7]);}", "  ctx.beginPath();ctx.moveTo(sx+82,sy);", "  ctx.quadraticCurveTo(sx+165,ry,rx-8,ry);ctx.stroke();ctx.setLineDash([]);", "  if(ra>0.95){", "    var tt=(time*0.45+i*0.33)%1;",
    
    "    var pp=QP(tt,sx+82,sy,sx+165,ry,rx-8,ry);", "    ctx.fillStyle='#fff';ctx.shadowColor=r[1];ctx.shadowBlur=10;",
    
    "    ctx.beginPath();ctx.arc(pp[0],pp[1],4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;", "  }", "  var sl=(1-ra)*18;", "  ctx.globalAlpha=ra;", "  ctx.fillStyle='rgba(16,21,26,0.85)';RR(rx,ry-38+sl,380,76,14);ctx.fill();", "  ctx.globalAlpha=ra*0.55;ctx.strokeStyle=r[1];ctx.lineWidth=1.5;", "  RR(rx,ry-38+sl,380,76,14);ctx.stroke();", "  ctx.globalAlpha=ra;", "  var icx=rx+40,icy=ry+sl;", "  ctx.strokeStyle=r[1];ctx.lineWidth=2.5;", "  ctx.beginPath();ctx.arc(icx,icy,18,0,Math.PI*2);ctx.stroke();", "  if(r[2]==='check'){ctx.beginPath();ctx.moveTo(icx-8,icy+1);ctx.lineTo(icx-2,icy+8);ctx.lineTo(icx+9,icy-7);ctx.stroke();}", "  if(r[2]==='dot'){ctx.fillStyle=r[1];ctx.beginPath();ctx.arc(icx,icy,5,0,Math.PI*2);ctx.fill();}", "  if(r[2]==='x'){ctx.beginPath();ctx.moveTo(icx-7,icy-7);ctx.lineTo(icx+7,icy+7);ctx.moveTo(icx+7,icy-7);ctx.lineTo(icx-7,icy+7);ctx.stroke();}", "  ctx.fillStyle=r[1];ctx.textAlign='left';", "  var fs=28;ctx.font='bold '+fs+'px Segoe UI, sans-serif';", "  while(ctx.measureText(r[0]).width>290&&fs>20){fs-=2;ctx.font='bold '+fs+'px Segoe UI, sans-serif';}", "  ctx.fillText(r[0],rx+74,ry+sl);", "  ctx.globalAlpha=1;", "});", "ctx.restore();"], 520)

def td_sandbox(title="Sandbox thực thi", tools=None, gate="Hỏi bạn trước", result="Kết quả thu về", side_left="Giới hạn tool", side_right="Ngân sách", top="Số vòng tối đa", color="green"):
    if not tools:
        tools = ["📄", "🔍", ">_"]
    acc = ACCENT.get(color, ACCENT["green"])
    return scene([QP, "var TOOLS=" + json.dumps(list(tools)[:3], ensure_ascii=False) + ";", "var TITLE=" + json.dumps(title, ensure_ascii=False) + ";", "var GATE=" + json.dumps(gate, ensure_ascii=False) + ";", "var RES=" + json.dumps(result, ensure_ascii=False) + ";", "var SL=" + json.dumps(side_left, ensure_ascii=False) + ";", "var SR=" + json.dumps(side_right, ensure_ascii=False) + ";", "var TP=" + json.dumps(top, ensure_ascii=False) + ";", "var AC=" + json.dumps(acc) + ";", "var NC=['#22d3ee','#34d399','#fbbf24'];", "var base=cursorY;", "var fx=70,fw=W-140,fy=base+70,fh=470;", "ctx.save();ctx.textBaseline='middle';", "/* chip TRÊN giữa (ngoài khung) */", "var ac0=CL(P*2-1.1);",
    
    "if(ac0>0){ctx.globalAlpha=ac0;", "ctx.font='24px Segoe UI, sans-serif';", "var tw0=ctx.measureText(TP).width+76;", "ctx.fillStyle='#10151a';RR(W/2-tw0/2,base+8,tw0,42,21);ctx.fill();", "ctx.strokeStyle='rgba(255,255,255,0.22)';ctx.lineWidth=1.5;RR(W/2-tw0/2,base+8,tw0,42,21);ctx.stroke();", "ctx.strokeStyle='#9aa3ad';ctx.lineWidth=2;", "ctx.beginPath();ctx.arc(W/2-tw0/2+26,base+29,9,0.5,Math.PI*2-0.6);ctx.stroke();", "ctx.fillStyle='#9aa3ad';", "ctx.beginPath();ctx.moveTo(W/2-tw0/2+34,base+21);ctx.lineTo(W/2-tw0/2+40,base+25);ctx.lineTo(W/2-tw0/2+32,base+28);ctx.closePath();ctx.fill();", "ctx.textAlign='left';ctx.fillText(TP,W/2-tw0/2+46,base+30);", "ctx.globalAlpha=1;}",
    
    "/* khung sandbox: nền mờ + 4 góc ngoặc */", "var af=EZ(CL(P*1.8));", "if(af>0){ctx.globalAlpha=af;", "ctx.fillStyle='rgba(16,21,26,0.7)';RR(fx,fy,fw,fh,18);ctx.fill();", "ctx.strokeStyle='rgba(255,255,255,0.07)';ctx.lineWidth=1;RR(fx,fy,fw,fh,18);ctx.stroke();", "ctx.strokeStyle=AC;ctx.lineWidth=3;ctx.lineCap='round';", "ctx.beginPath();ctx.moveTo(fx+46,fy);ctx.lineTo(fx+6,fy);ctx.lineTo(fx+6,fy+46);", "ctx.moveTo(fx+fw-46,fy);ctx.lineTo(fx+fw-6,fy);ctx.lineTo(fx+fw-6,fy+46);", "ctx.moveTo(fx+46,fy+fh);ctx.lineTo(fx+6,fy+fh);ctx.lineTo(fx+6,fy+fh-46);", "ctx.moveTo(fx+fw-46,fy+fh);ctx.lineTo(fx+fw-6,fy+fh);ctx.lineTo(fx+fw-6,fy+fh-46);", "ctx.stroke();ctx.lineCap='butt';", "/* chip tiêu đề mép trên trái */", "ctx.font='bold 22px Consolas, monospace';", "var ttw=ctx.measureText(TITLE).width+36;", "ctx.fillStyle='#10151a';RR(fx+64,fy-18,ttw,36,18);ctx.fill();", "ctx.strokeStyle=AC;ctx.lineWidth=1.5;RR(fx+64,fy-18,ttw,36,18);ctx.stroke();", "ctx.fillStyle=AC;ctx.textAlign='left';ctx.fillText(TITLE,fx+82,fy+1);",
    
    "ctx.globalAlpha=1;}", "/* nhãn tím: yêu cầu tool vào + mũi tên đứt dẫn vào node */", "var nx=fx+280,ncys=[fy+122,fy+234,fy+346];",
    
    "var ap=CL(P*2-0.3);", "if(ap>0){ctx.globalAlpha=ap*af;", "ctx.fillStyle='#a78bfa';", "ctx.beginPath();ctx.arc(fx+46,fy+48,5,0,Math.PI*2);ctx.fill();", "ctx.font='22px Segoe UI, sans-serif';ctx.textAlign='left';", "ctx.fillText('yêu cầu tool vào',fx+60,fy+48);", "ctx.strokeStyle='rgba(167,139,250,0.55)';ctx.lineWidth=2;", "ctx.setLineDash([7,6]);ctx.lineDashOffset=-time*24;", "ctx.beginPath();", "for(var k=0;k<3;k++){var ky=ncys[k];ctx.moveTo(nx-70,ky);ctx.lineTo(nx-14,ky);}", "ctx.stroke();ctx.setLineDash([]);", "ctx.fillStyle='rgba(167,139,250,0.75)';", "for(var k2=0;k2<3;k2++){var ky2=ncys[k2];", "  ctx.beginPath();ctx.moveTo(nx-8,ky2);ctx.lineTo(nx-19,ky2-6);ctx.lineTo(nx-19,ky2+6);ctx.closePath();ctx.fill();}", "ctx.globalAlpha=1;}", "/* 3 node tool xếp dọc */", "TOOLS.forEach(function(tl,i){", "  var na=EZ(CL(P*2-0.35-i*0.18));if(na<=0)return;", "  var ncy=ncys[i],sl=(1-na)*16;", "  ctx.globalAlpha=na;", "  ctx.fillStyle='rgba(16,21,26,0.9)';RR(nx,ncy-42+sl,84,84,14);ctx.fill();", "  ctx.strokeStyle=NC[i];ctx.lineWidth=1.5;ctx.globalAlpha=na*0.8;", "  RR(nx,ncy-42+sl,84,84,14);ctx.stroke();ctx.globalAlpha=na;", "  ctx.textAlign='center';ctx.fillStyle='#e6edf3';", "  ctx.font=(tl.length<=2&&tl.charCodeAt(0)<127)?'bold 34px Consolas, monospace':'40px Segoe UI, sans-serif';", "  ctx.fillText(tl,nx+42,ncy+sl+3);", "  ctx.globalAlpha=1;", "});", "/* hộp thu kết quả bên phải + 3 đường cong nối */", "var ab=EZ(CL(P*2-0.8));", "var bx=fx+600,bw=120,bh=110,bcy=fy+205;", "if(ab>0){", "  TOOLS.forEach(function(tl,i){", "    var ncy=ncys[i],ey=bcy-34+i*34;", "    var qx=(nx+90+bx)/2;", "    ctx.globalAlpha=ab*0.65;ctx.strokeStyle=NC[i];ctx.lineWidth=2;",
    
    "    ctx.beginPath();ctx.moveTo(nx+90,ncy);", "    ctx.quadraticCurveTo(qx,ncy,bx-8,ey);ctx.stroke();", "    if(ab>0.95){", "      var tt=(time*0.4+i*0.33)%1;", "      var pp=QP(tt,nx+90,ncy,qx,ncy,bx-8,ey);", "      ctx.globalAlpha=1;ctx.fillStyle='#fff';ctx.shadowColor=NC[i];ctx.shadowBlur=10;", "      ctx.beginPath();ctx.arc(pp[0],pp[1],4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;", "    }", "  });", "  ctx.globalAlpha=ab;", "  ctx.fillStyle='rgba(16,21,26,0.9)';RR(bx,bcy-bh/2,bw,bh,14);ctx.fill();", "  ctx.strokeStyle='#38bdf8';ctx.lineWidth=1.5;ctx.globalAlpha=ab*0.8;", "  RR(bx,bcy-bh/2,bw,bh,14);ctx.stroke();ctx.globalAlpha=ab;", "  ctx.textAlign='center';ctx.font='44px Segoe UI, sans-serif';", "  ctx.fillText('\\ud83d\\udce5',bx+bw/2,bcy+2);", "  ctx.fillStyle='#38bdf8';ctx.font='24px Segoe UI, sans-serif';", "  wrapText(RES,190,'24px Segoe UI, sans-serif').slice(0,2).forEach(function(l,i){", "    ctx.fillText(l,bx+bw/2,bcy+bh/2+28+i*28);});", "  ctx.globalAlpha=1;", "}", "/* pill cam: cổng hỏi người dùng */", "var ag=EZ(CL(P*2-1));", "if(ag>0){ctx.globalAlpha=ag;", "var gt='\\u2713 '+GATE;", "ctx.font='bold 26px Segoe UI, sans-serif';", "var gw=ctx.measureText(gt).width+56;", "var gy=fy+fh-74;", "ctx.fillStyle='rgba(251,146,60,0.15)';RR(fx+fw/2-gw/2,gy,gw,52,26);ctx.fill();", "ctx.strokeStyle='#fb923c';ctx.lineWidth=2;", "ctx.shadowColor='#fb923c';ctx.shadowBlur=8+4*Math.sin(time*2.2);", "RR(fx+fw/2-gw/2,gy,gw,52,26);ctx.stroke();ctx.shadowBlur=0;", "ctx.fillStyle='#fb923c';ctx.textAlign='center';ctx.fillText(gt,fx+fw/2,gy+27);", "ctx.globalAlpha=1;}", "/* chip trái/phải cưỡi lên mép khung */",
    
    "var ac1=CL(P*2-1.1);", "if(ac1>0){ctx.globalAlpha=ac1;", "ctx.font='24px Segoe UI, sans-serif';", "var lw1=ctx.measureText(SL).width+66;", "var ly=fy+fh/2-21;", "ctx.fillStyle='#10151a';RR(60,ly,lw1,42,21);ctx.fill();", "ctx.strokeStyle='rgba(255,255,255,0.22)';ctx.lineWidth=1.5;RR(60,ly,lw1,42,21);ctx.stroke();", "ctx.textAlign='left';ctx.font='20px Segoe UI, sans-serif';", "ctx.fillText('\\ud83d\\udd12',76,ly+21);", "ctx.fillStyle='#9aa3ad';ctx.font='24px Segoe UI, sans-serif';", "ctx.fillText(SL,108,ly+22);", "var rw1=ctx.measureText(SR).width+92;", "var rx1=W-60-rw1;", "ctx.fillStyle='#10151a';RR(rx1,ly,rw1,42,21);ctx.fill();", "ctx.strokeStyle='rgba(255,255,255,0.22)';RR(rx1,ly,rw1,42,21);ctx.stroke();", "for(var b=0;b<3;b++){", "  ctx.fillStyle=b<2?'#fbbf24':'rgba(251,191,36,0.35)';", "  ctx.fillRect(rx1+18+b*12,ly+13,8,16);", "}", "ctx.fillStyle='#9aa3ad';ctx.fillText(SR,rx1+62,ly+22);", "ctx.globalAlpha=1;}", "ctx.restore();"], 560)

def td_context_gauge(pct=88, items=None, note="đều chiếm chỗ trong cửa sổ"):
    if not items:
        items = [{"label": "User prompt", "color": "cyan"},
        {"label": "System prompt", "color": "yellow"},
        {"label": "Phản hồi Claude", "color": "green"},
        {"label": "Định nghĩa tool", "color": "purple"},
        {"label": "Tool input", "color": "orange"},
        {"label": "Tool output", "color": "red"}]
    payload = json.dumps(
        [{"label": it.get("label", ""), "c": ACCENT.get(it.get("color", "cyan"), ACCENT["cyan"])} for it in items[:6]],
        ensure_ascii=False,
    )
    return scene(["var ITEMS=" + payload + ";", "var PCT=" + str(max(0, min(100, int(pct)))) + ";", "var NOTE=" + json.dumps(note, ensure_ascii=False) + ";", "var base=cursorY;", "ctx.save();ctx.textBaseline='middle';", "/* cột gauge bên trái */", "var gx=70,gy=base+16,gw=180,gh=520;", "var ga=EZ(CL(P*1.8));", "ctx.globalAlpha=ga;", "ctx.fillStyle='rgba(16,21,26,0.85)';RR(gx,gy,gw,gh,24);ctx.fill();", "ctx.strokeStyle='rgba(255,255,255,0.14)';ctx.lineWidth=1.5;RR(gx,gy,gw,gh,24);ctx.stroke();", "/* vạch chia 25/50/75 */", "ctx.strokeStyle='rgba(255,255,255,0.1)';ctx.lineWidth=1;", "for(var t=1;t<4;t++){var ty=gy+12+(gh-24)*t/4;", "  ctx.beginPath();ctx.moveTo(gx+12,ty);ctx.lineTo(gx+34,ty);ctx.stroke();}", "/* phần đầy vàng dâng theo P */", "var ix=gx+12,iw=gw-24,iy=gy+12,ih=gh-24;", "var fr=(PCT/100)*EZ(P);", "var fhh=ih*fr,fy2=iy+ih-fhh;", "if(fhh>2){", "  var grd=ctx.createLinearGradient(0,iy+ih,0,fy2);", "  grd.addColorStop(0,'#f59e0b');grd.addColorStop(1,'#fbbf24');", "  ctx.fillStyle=grd;RR(ix,fy2,iw,fhh,10);ctx.fill();", "  ctx.globalAlpha=ga*0.12;ctx.strokeStyle='#000';ctx.lineWidth=1;", "  for(var s=1;s*44<fhh;s++){var sy2=iy+ih-s*44;", "    ctx.beginPath();ctx.moveTo(ix+6,sy2);ctx.lineTo(ix+iw-6,sy2);ctx.stroke();}", "  ctx.globalAlpha=ga;", "}", "/* nhãn % đen trên nền vàng, ngồi trên đỉnh phần đầy */", "var val=Math.round(PCT*EZ(P));", "var by2=Math.max(gy+10,Math.min(fy2-22,gy+gh-56));", "ctx.fillStyle='#fbbf24';RR(gx+gw/2-48,by2,96,44,10);ctx.fill();", "ctx.fillStyle='#0b0f14';ctx.font='bold 30px Segoe UI, sans-serif';ctx.textAlign='center';", "ctx.fillText(val+'%',gx+gw/2,by2+23);", "ctx.fillStyle='#9aa3ad';ctx.font='20px Consolas, monospace';", "ctx.fillText('context',gx+gw/2,gy+gh+26);", "ctx.globalAlpha=1;", "/* chips 2 cột x 3 hàng bên phải */", "var cx0=290,colw=(W-60-290-24)/2,rh=128,gap=22;", "var cy0=base+16+(gh-(3*rh+2*gap))/2;",
    
    "ITEMS.forEach(function(it,i){", "  var e=EZ(CL(P*2-0.25-i*0.12));if(e<=0)return;", "  var col=i%2,row=Math.floor(i/2);", "  var x=cx0+col*(colw+24),y=cy0+row*(rh+gap)+(1-e)*18;", "  var last=(i===ITEMS.length-1);", "  ctx.globalAlpha=e;", "  ctx.fillStyle='rgba(16,21,26,0.85)';RR(x,y,colw,rh,14);ctx.fill();", "  ctx.strokeStyle=it.c;",
    
    "  if(last){", "    ctx.lineWidth=3;ctx.globalAlpha=e*0.95;", "    ctx.shadowColor=it.c;ctx.shadowBlur=10+6*Math.sin(time*2.4);", "  }else{ctx.lineWidth=1.5;ctx.globalAlpha=e*0.55;}", "  RR(x,y,colw,rh,14);ctx.stroke();ctx.shadowBlur=0;", "  ctx.globalAlpha=e;ctx.textAlign='left';", "  ctx.fillStyle=it.c;ctx.font='bold 20px Consolas, monospace';", "  ctx.fillText('ngữ cảnh',x+24,y+34);", "  ctx.fillStyle='#f5f7f9';",
    
    "  var fs=28;ctx.font='bold '+fs+'px Segoe UI, sans-serif';", "  while(ctx.measureText(it.label).width>colw-48&&fs>20){fs-=2;ctx.font='bold '+fs+'px Segoe UI, sans-serif';}",
    
    "  ctx.fillText(it.label,x+24,y+84);", "  ctx.globalAlpha=1;", "});", "/* ghi chú dưới cùng */", "var na=CL(P*2-1);", "if(na>0){ctx.globalAlpha=na;", "ctx.fillStyle='#9aa3ad';ctx.font='24px Segoe UI, sans-serif';ctx.textAlign='center';", "ctx.fillText(NOTE,W/2,base+572);", "ctx.globalAlpha=1;}", "ctx.restore();"], 600)
    
SCENES = {"td_shield": {"fn": td_shield, "doc": 'td_shield {"input":"Yêu cầu hành động","policy":"Chính sách quyền","allow":"Được làm ngay","confirm":"Phải hỏi bạn","deny":"Không được làm"} — khiên chính sách đỏ chặn giữa: yêu cầu vào bên trái, 3 nhánh kết quả (được làm/hỏi lại/cấm) bên phải', "demo": {"input": "Yêu cầu hành động", "policy": "Chính sách quyền", "allow": "Được làm ngay", "confirm": "Phải hỏi bạn", "deny": "Không được làm"}}, "td_sandbox": {"fn": td_sandbox, "doc": 'td_sandbox {"title":"Sandbox thực thi","tools":["📄","🔍",">_"],"gate":"Hỏi bạn trước","result":"Kết quả thu về","side_left":"Giới hạn tool","side_right":"Ngân sách","top":"Số vòng tối đa","color":"green"} — hộp cát 4 góc ngoặc: tool chạy trong khung có giới hạn, cổng hỏi người dùng', "demo": {"title": "Sandbox thực thi", "tools": ["📄", "🔍", ">_"], "gate": "Hỏi bạn trước", "result": "Kết quả thu về", "side_left": "Giới hạn tool", "side_right": "Ngân sách", "top": "Số vòng tối đa", "color": "green"}}, "td_context_gauge": {"fn": td_context_gauge, "doc": 'td_context_gauge {"pct":88,"items":[{"label":"User prompt","color":"cyan"}],"note":"đều chiếm chỗ trong cửa sổ"} — thước ngữ cảnh % dâng vàng bên trái + lưới chip thành phần chiếm chỗ (item cuối glow nhấn mạnh)', "demo": {"pct": 88, "items": [{"label": "User prompt", "color": "cyan"},
    {"label": "System prompt", "color": "yellow"},
    {"label": "Phản hồi Claude", "color": "green"},
    {"label": "Định nghĩa tool", "color": "purple"},
    {"label": "Tool input", "color": "orange"},
    {"label": "Tool output", "color": "red"}], "note": "đều chiếm chỗ trong cửa sổ"}}}
