"""core/scenes_td_2.py — Bộ scene techdark (phần 2): td_pipeline, td_turn_ring, td_hex_chain.

Phong cách "Mổ Xẻ Công Nghệ": nền than chì do renderer lo, linh kiện viền mảnh
màu theo section, tag chip nhỏ, chữ trắng đậm. Xem td_spec.md.
"""
import json
from core.custom_scenes import scene; ACCENTS = {"cyan": "#22d3ee", "green": "#34d399", "orange": "#fb923c", "yellow": "#fbbf24", "red": "#f87171", "purple": "#a78bfa", "blue": "#38bdf8"}; _ACC_JS = "var ACC=" + json.dumps(ACCENTS) + ";"; TXT = "#f5f7f9"; MUTED = "#9aa3ad"; CARD_BG = "rgba(16,21,26,0.85)"
def _hex_to_rgba(hx, a):
    hx = hx.lstrip("#"); b = int(hx[4:6], 16); g = int(hx[2:4], 16); r = int(hx[0:2], 16)
    return "rgba(%d,%d,%d,%s)" % (r, g, b, a)

def td_pipeline(steps=None, active=2, note=""):
    if not steps:
        steps = [{"en": "Receive prompt", "vi": "Tiếp nhận", "icon": "📥", "color": "cyan"},
            {"en": "Assess state", "vi": "Đánh giá", "icon": "🧭", "color": "blue"},
            {"en": "Call tool", "vi": "Gọi công cụ", "icon": "🛠", "color": "yellow"},
            {"en": "Get result", "vi": "Nhận kết quả", "icon": "📤", "color": "orange"},
            {"en": "Iterate", "vi": "Lặp tiếp", "icon": "🔁", "color": "green"}]
    defaults = ["cyan", "blue", "yellow", "orange", "green"]
    for i, s in enumerate(steps):
        s.setdefault("color", defaults[i % len(defaults)])
    payload = json.dumps(steps, ensure_ascii=False); height = 330 + (44 if note else 0)
    return scene([_ACC_JS, "var STEPS=" + payload + ";", "var ACT=" + str(int(active)) + ";", "var NOTE=" + json.dumps(note or "", ensure_ascii=False) + ";", "var n=STEPS.length, bw=96;", "var pitch=n>1?(W-2*MX-bw)/(n-1):0;", "var by=cursorY+44;", "ctx.save();ctx.textBaseline='middle';", "/* mui ten dut net giua cac hop */", "for(var i=0;i<n-1;i++){", "  var rp=CL(P*2.5-0.35*(i+1));if(rp<=0)continue;", "  var x1=MX+bw/2+i*pitch+bw/2+14, x2=MX+bw/2+(i+1)*pitch-bw/2-14;", "  var ay=by+bw/2;", "  ctx.globalAlpha=Math.min(1,rp*1.4);", "  ctx.strokeStyle='rgba(154,163,173,0.75)';ctx.lineWidth=2.5;", "  ctx.setLineDash([8,6]);ctx.lineDashOffset=-time*30;", "  ctx.beginPath();ctx.moveTo(x1,ay);ctx.lineTo(x2-12,ay);ctx.stroke();ctx.setLineDash([]);", "  ctx.fillStyle='rgba(154,163,173,0.9)';", "  ctx.beginPath();ctx.moveTo(x2,ay);ctx.lineTo(x2-13,ay-7);ctx.lineTo(x2-13,ay+7);ctx.closePath();ctx.fill();", "  ctx.globalAlpha=1;", "}", "STEPS.forEach(function(st,i){", "  var rp=CL(P*2.5-0.35*i);if(rp<=0)return;", "  var e=EZ(rp), cx=MX+bw/2+i*pitch, dy=18*(1-e);", "  var ac=ACC[st.color]||ACC.cyan;", "  ctx.globalAlpha=Math.min(1,rp*1.5);", "  /* so thu tu tren hop */", "  ctx.font='bold 20px Consolas, monospace';ctx.textAlign='center';", "  ctx.fillStyle=(i===ACT)?ac:'#9aa3ad';", "  ctx.fillText('0'+(i+1),cx,cursorY+22+dy);", "  /* hop icon */", "  var bx=cx-bw/2, byy=by+dy;", "  if(i===ACT){", "    ctx.fillStyle=ac;ctx.globalAlpha=Math.min(1,rp*1.5)*0.12;RR(bx,byy,bw,bw,14);ctx.fill();", "    ctx.globalAlpha=Math.min(1,rp*1.5);", "    ctx.shadowColor=ac;ctx.shadowBlur=13+4*Math.sin(time*3);", "    ctx.strokeStyle=ac;ctx.lineWidth=2.5;RR(bx,byy,bw,bw,14);ctx.stroke();ctx.shadowBlur=0;", "  }else{", "    ctx.fillStyle='rgba(16,21,26,0.85)';RR(bx,byy,bw,bw,14);ctx.fill();", "    ctx.strokeStyle=ac;ctx.globalAlpha=Math.min(1,rp*1.5)*0.55;ctx.lineWidth=1.5;RR(bx,byy,bw,bw,14);ctx.stroke();", "    ctx.globalAlpha=Math.min(1,rp*1.5);", "  }", "  ctx.font='44px sans-serif';ctx.fillStyle='#f5f7f9';", "  ctx.fillText(st.icon||'',cx,byy+bw/2+2);", "  /* nhan EN + VI */", "  var fs=24;ctx.font='bold '+fs+'px Segoe UI, sans-serif';", "  while(ctx.measureText(st.en||'').width>pitch-20&&fs>17){fs-=1;ctx.font='bold '+fs+'px Segoe UI, sans-serif';}", "  ctx.fillStyle=(i===ACT)?ac:'#f5f7f9';", "  ctx.fillText(st.en||'',cx,by+bw+36+dy);", "  var fv=22;ctx.font=fv+'px Segoe UI, sans-serif';",
    
    "  while(ctx.measureText(st.vi||'').width>pitch-20&&fv>16){fv-=1;ctx.font=fv+'px Segoe UI, sans-serif';}", "  ctx.fillStyle='#9aa3ad';", "  ctx.fillText(st.vi||'',cx,by+bw+68+dy);", "  ctx.globalAlpha=1;", "});", "if(NOTE){", "  var np=CL(P*2.5-1.6);", "  if(np>0){",
    
    "    ctx.globalAlpha=Math.min(1,np*1.5);", "    ctx.font='24px Segoe UI, sans-serif';ctx.fillStyle='#9aa3ad';ctx.textAlign='center';", "    ctx.fillText(NOTE,W/2,cursorY+296+10*(1-EZ(np)));", "    ctx.globalAlpha=1;", "  }", "}", "ctx.restore();"], height)

def td_turn_ring(word="turn", sub="vòng lặp đầy đủ", orbits=None, items=None, color="orange"):
    if not orbits:
        orbits = ["Vòng 1", "Vòng 2", "Vòng 3"]
    if not items:
        items = ["Xem trạng thái", "Sinh phản hồi", "Gọi công cụ", "Nhận kết quả", "Đánh giá tiếp"]
    ac = ACCENTS.get(color, ACCENTS["orange"])
    return scene(["var ORB=" + json.dumps(list(orbits)[:3], ensure_ascii=False) + ";", "var ITEMS=" + json.dumps(list(items)[:5], ensure_ascii=False) + ";", "var WORD=" + json.dumps(word, ensure_ascii=False) + ";", "var SUB=" + json.dumps(sub, ensure_ascii=False) + ";",
    
    "var AC=" + json.dumps(ac) + ";", "var ACA=" + json.dumps(_hex_to_rgba(ac, 0.55)) + ";", "var cx=300, cy=cursorY+232;", "var radii=[90,140,190], alphas=[0.9,0.62,0.4];", "var angs=[-1.5708,2.62,-2.3];", "var rev=EZ(CL(P*1.7));", "ctx.save();ctx.textBaseline='middle';ctx.textAlign='center';", "ctx.translate(cx,cy);ctx.scale(rev,rev);ctx.translate(-cx,-cy);", "ctx.globalAlpha=Math.min(1,P*2.2);", "/* 3 vong dong tam net dut quay */", "for(var i=0;i<3;i++){", "  ctx.strokeStyle=AC;ctx.globalAlpha=Math.min(1,P*2.2)*alphas[i];", "  ctx.lineWidth=2;ctx.setLineDash([12,9]);", "  ctx.lineDashOffset=(i%2?1:-1)*time*(22+i*6);", "  ctx.beginPath();ctx.arc(cx,cy,radii[i],0,Math.PI*2);ctx.stroke();", "  ctx.setLineDash([]);", "}", "ctx.globalAlpha=Math.min(1,P*2.2);", "/* cham sang chay theo vong ngoai */", "var da=-Math.PI/2+time*1.1;", "ctx.fillStyle='#ffffff';ctx.shadowColor=AC;ctx.shadowBlur=14;", "ctx.beginPath();ctx.arc(cx+Math.cos(da)*190,cy+Math.sin(da)*190,6,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;", "/* tam: word + sub */",
    
    "var wf=56;ctx.font='bold '+wf+'px Segoe UI, sans-serif';", "while(ctx.measureText(WORD).width>158&&wf>30){wf-=2;ctx.font='bold '+wf+'px Segoe UI, sans-serif';}", "ctx.fillStyle='#f5f7f9';ctx.shadowColor=AC;ctx.shadowBlur=10;", "ctx.fillText(WORD,cx,cy-14);ctx.shadowBlur=0;", "var sf=24;ctx.font=sf+'px Segoe UI, sans-serif';", "while(ctx.measureText(SUB).width>148&&sf>14){sf-=1;ctx.font=sf+'px Segoe UI, sans-serif';}", "ctx.fillStyle='#9aa3ad';ctx.fillText(SUB,cx,cy+28);", "/* pill nhan tren moi vong */", "ORB.forEach(function(ob,i){", "  var px=cx+Math.cos(angs[i])*radii[i], py=cy+Math.sin(angs[i])*radii[i];", "  ctx.font='22px Segoe UI, sans-serif';", "  var tw=ctx.measureText(ob).width, pw=tw+26, ph=34;", "  ctx.fillStyle='rgba(16,21,26,0.85)';RR(px-pw/2,py-ph/2,pw,ph,17);ctx.fill();", "  ctx.strokeStyle=ACA;ctx.lineWidth=1.5;RR(px-pw/2,py-ph/2,pw,ph,17);ctx.stroke();",
    
    "  ctx.fillStyle=AC;ctx.fillText(ob,px,py+1);", "});", "ctx.restore();", "/* danh sach buoc ben phai */", "ctx.save();ctx.textBaseline='middle';", "var lx=560, lw=W-70-lx;", "ITEMS.forEach(function(it,i){", "  var rp=CL(P*2.4-0.15*i);if(rp<=0)return;", "  var e=EZ(rp), ry=cursorY+22+i*84, dx=26*(1-e);", "  ctx.globalAlpha=Math.min(1,rp*1.5);", "  ctx.fillStyle='rgba(16,21,26,0.85)';RR(lx+dx,ry,lw,70,14);ctx.fill();", "  ctx.strokeStyle='rgba(255,255,255,0.12)';ctx.lineWidth=1.5;RR(lx+dx,ry,lw,70,14);ctx.stroke();", "  ctx.font='bold 28px Consolas, monospace';ctx.textAlign='left';", "  ctx.fillStyle=" + json.dumps(ac) + ";", "  ctx.fillText('0'+(i+1),lx+dx+24,ry+36);", "  var lf=28;ctx.font=lf+'px Segoe UI, sans-serif';", "  while(ctx.measureText(it).width>lw-118&&lf>20){lf-=1;ctx.font=lf+'px Segoe UI, sans-serif';}", "  ctx.fillStyle='#f5f7f9';ctx.fillText(it,lx+dx+92,ry+36);", "  ctx.globalAlpha=1;", "});", "ctx.restore();"], 460)

def td_hex_chain(turns=None, sub="trạng thái → phản hồi", inputs=None, final="Phản hồi cuối", color="orange"):
    if not turns:
        turns = ["Turn 01", "Turn 02", "Turn 03"]
    if not inputs:
        inputs = ["Prompt hiện tại", "System prompt", "Định nghĩa tool", "Lịch sử"]
    ac = ACCENTS.get(color, ACCENTS["orange"]); chip_colors = [ACCENTS["cyan"], ACCENTS["yellow"], ACCENTS["green"], ACCENTS["purple"]]
    return scene(["var TURNS=" + json.dumps(list(turns)[:3], ensure_ascii=False) + ";", "var SUB=" + json.dumps(sub, ensure_ascii=False) + ";", "var INPUTS=" + json.dumps(list(inputs)[:4], ensure_ascii=False) + ";", "var FINAL=" + json.dumps(final, ensure_ascii=False) + ";", "var AC=" + json.dumps(ac) + ";", "var ACA=" + json.dumps(_hex_to_rgba(ac, 0.55)) + ";", "var CCOL=" + json.dumps(chip_colors) + ";", "var PUR='#a78bfa';", "ctx.save();ctx.textBaseline='middle';", "/* cot chips inputs ben trai */",
    
    "var chY=cursorY+120;", "ctx.font='22px Segoe UI, sans-serif';ctx.textAlign='left';", "ctx.globalAlpha=Math.min(1,P*2.5);", "ctx.fillStyle='#9aa3ad';ctx.fillText('mỗi vòng thấy',MX+4,chY-24);", "ctx.globalAlpha=1;", "INPUTS.forEach(function(inp,i){", "  var rp=CL(P*2.2-0.12*i);if(rp<=0)return;", "  var e=EZ(rp), ry=chY+i*70, dx=-24*(1-e);", "  ctx.font='24px Segoe UI, sans-serif';", "  var tw=ctx.measureText(inp).width, cw=Math.max(190,tw+36);", "  ctx.globalAlpha=Math.min(1,rp*1.5);", "  ctx.fillStyle='rgba(16,21,26,0.85)';RR(MX+dx,ry,cw,54,12);ctx.fill();", "  ctx.strokeStyle=CCOL[i%4];ctx.globalAlpha=Math.min(1,rp*1.5)*0.65;ctx.lineWidth=1.5;RR(MX+dx,ry,cw,54,12);ctx.stroke();", "  ctx.globalAlpha=Math.min(1,rp*1.5);", "  ctx.fillStyle='#f5f7f9';ctx.fillText(inp,MX+dx+18,ry+28);", "  ctx.globalAlpha=1;", "});",
    
    "/* luc giac cheo len */", "function hexPath(hx,hy,r){ctx.beginPath();for(var k=0;k<6;k++){var a=-Math.PI/2+k*Math.PI/3;var px=hx+Math.cos(a)*r,py=hy+Math.sin(a)*r;if(k===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}ctx.closePath();}", "var HX=[400,590,780], HY=[cursorY+440,cursorY+315,cursorY+190], HR=92;", "var docX=940, docY=cursorY+75;",
    
    "/* duong noi net dut cheo + hat sang */", "for(var j=0;j<3;j++){", "  var rp=CL(P*2.2-0.6-0.3*j);if(rp<=0)continue;", "  var x1=HX[j],y1=HY[j],x2,y2;", "  if(j<2){x2=HX[j+1];y2=HY[j+1];}else{x2=docX;y2=docY;}", "  var dd=Math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1));", "  var ux=(x2-x1)/dd, uy=(y2-y1)/dd;", "  var pad1=HR+8, pad2=(j<2)?HR+8:76;", "  var sx=x1+ux*pad1, sy=y1+uy*pad1, ex=x2-ux*pad2, ey=y2-uy*pad2;", "  ctx.globalAlpha=Math.min(1,rp*1.4)*0.8;", "  ctx.strokeStyle=AC;ctx.lineWidth=2;", "  ctx.setLineDash([9,7]);ctx.lineDashOffset=-time*28;", "  ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(ex,ey);ctx.stroke();ctx.setLineDash([]);", "  var tt=(time*0.45+j*0.33)%1;", "  var px=sx+(ex-sx)*tt, py=sy+(ey-sy)*tt;", "  ctx.fillStyle='#ffffff';ctx.shadowColor=AC;ctx.shadowBlur=12;", "  ctx.beginPath();ctx.arc(px,py,4.5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;", "  ctx.globalAlpha=1;", "}", "TURNS.forEach(function(tn,j){", "  var rp=CL(P*2.2-0.45-0.3*j);if(rp<=0)return;", "  var e=EZ(rp), hx=HX[j], hy=HY[j]+16*(1-e);", "  ctx.globalAlpha=Math.min(1,rp*1.5);", "  hexPath(hx,hy,HR);ctx.fillStyle='rgba(16,21,26,0.85)';ctx.fill();", "  ctx.strokeStyle=AC;ctx.lineWidth=2;", "  ctx.shadowColor=AC;ctx.shadowBlur=9;", "  hexPath(hx,hy,HR);ctx.stroke();ctx.shadowBlur=0;", "  ctx.textAlign='center';", "  ctx.fillStyle='#f5f7f9';ctx.font='bold 30px Segoe UI, sans-serif';", "  ctx.fillText(tn,hx,hy-14);", "  var sf=20;ctx.font=sf+'px Segoe UI, sans-serif';", "  while(ctx.measureText(SUB).width>146&&sf>13){sf-=1;ctx.font=sf+'px Segoe UI, sans-serif';}", "  ctx.fillStyle='#9aa3ad';ctx.fillText(SUB,hx,hy+22);", "  ctx.globalAlpha=1;", "});", "/* icon tai lieu cuoi + nhan final */", "var dp=CL(P*2.2-1.5);", "if(dp>0){", "  var de=EZ(dp), dw=90, dh=110;", "  var dx0=docX-dw/2, dy0=docY-dh/2+14*(1-de);", "  ctx.globalAlpha=Math.min(1,dp*1.5);", "  ctx.fillStyle='rgba(16,21,26,0.85)';RR(dx0,dy0,dw,dh,10);ctx.fill();", "  ctx.strokeStyle=PUR;ctx.lineWidth=2.5;", "  ctx.shadowColor=PUR;ctx.shadowBlur=12+4*Math.sin(time*2.6);", "  RR(dx0,dy0,dw,dh,10);ctx.stroke();ctx.shadowBlur=0;", "  ctx.strokeStyle='rgba(167,139,250,0.8)';ctx.lineWidth=3;ctx.lineCap='round';", "  ctx.beginPath();ctx.moveTo(dx0+18,dy0+34);ctx.lineTo(dx0+72,dy0+34);ctx.stroke();", "  ctx.beginPath();ctx.moveTo(dx0+18,dy0+56);ctx.lineTo(dx0+72,dy0+56);ctx.stroke();", "  ctx.beginPath();ctx.moveTo(dx0+18,dy0+78);ctx.lineTo(dx0+54,dy0+78);ctx.stroke();ctx.lineCap='butt';", "  var ff=26;ctx.font='bold '+ff+'px Segoe UI, sans-serif';ctx.textAlign='center';", "  while(ctx.measureText(FINAL).width>170&&ff>18){ff-=1;ctx.font='bold '+ff+'px Segoe UI, sans-serif';}", "  ctx.fillStyle='#f5f7f9';ctx.shadowColor=PUR;ctx.shadowBlur=10;", "  ctx.fillText(FINAL,docX,dy0+dh+28);ctx.shadowBlur=0;", "  ctx.globalAlpha=1;", "}", "ctx.restore();"], 560)

SCENES = {"td_pipeline": {"fn": td_pipeline, "doc": 'td_pipeline {"steps":[{"en":"Receive prompt","vi":"Tiếp nhận","icon":"📥","color":"cyan"}],"active":2,"note":"..."} — 5 hộp icon ngang nối mũi tên đứt chạy, bước active glow, nhãn EN/VI, chú thích cuối', "demo": {"steps": [{"en": "Receive prompt", "vi": "Tiếp nhận", "icon": "📥", "color": "cyan"},
    {"en": "Assess state", "vi": "Đánh giá", "icon": "🧭", "color": "blue"},
    {"en": "Call tool", "vi": "Gọi công cụ", "icon": "🛠", "color": "yellow"},
    {"en": "Get result", "vi": "Nhận kết quả", "icon": "📤", "color": "orange"},
    {"en": "Iterate", "vi": "Lặp tiếp", "icon": "🔁", "color": "green"}], "active": 2, "note": "Mỗi vòng đều đi qua đủ 5 bước — không bước nào là phép màu"}}, "td_turn_ring": {"fn": td_turn_ring, "doc": 'td_turn_ring {"word":"turn","sub":"vòng lặp đầy đủ","orbits":["Vòng 1","Vòng 2","Vòng 3"],"items":["..."],"color":"orange"} — vòng đồng tâm nét đứt quay + pill nhãn + danh sách 5 bước bên phải', "demo": {"word": "turn", "sub": "vòng lặp đầy đủ", "orbits": ["Vòng 1", "Vòng 2", "Vòng 3"], "items": ["Xem trạng thái", "Sinh phản hồi", "Gọi công cụ", "Nhận kết quả", "Đánh giá tiếp"], "color": "orange"}}, "td_hex_chain": {"fn": td_hex_chain, "doc": 'td_hex_chain {"turns":["Turn 01","Turn 02","Turn 03"],"sub":"trạng thái → phản hồi","inputs":["..."],"final":"Phản hồi cuối","color":"orange"} — chips input trái + 3 lục giác chéo lên nối nét đứt + icon tài liệu cuối', "demo": {"turns": ["Turn 01", "Turn 02", "Turn 03"], "sub": "trạng thái → phản hồi", "inputs": ["Prompt hiện tại", "System prompt", "Định nghĩa tool", "Lịch sử"], "final": "Phản hồi cuối", "color": "orange"}}}
